import{V,add,sub,mul,dot,length,unit,clamp,color,Geometry}from'./engine3d.js?v=20261006achv';
import{Simulation,makeHero,firstWall,PALETTE}from'./world3d.js?v=20261006achv';
import{DEFAULT_SETTINGS,applySettings}from'./settings-model.js?v=20261006achv';
import {heroPose,updateHeroPose} from './hero-pose.js?v=20261006achv';
const neon=[.3,1.6,2],orange=[1.9,.65,.18];
export class Adventure extends Simulation{
 constructor(world){super(world);this.options={...DEFAULT_SETTINGS};this.weatherClock=0;this.airAttachCount=0;this.aimPitch=0;this.hanging=null;this.stuntChallenge=null;this.character='peter';this.style=0;this.combo=0;this.comboTime=0;this.flip=0;this.flipKind=0;this.boostTime=0;this.zipTime=0;this.zipTarget=null;this.cooldowns={};this.slowTime=0;this.netTime=0;this.suitType=0;this.weather='clear';this.dayTime=.8;this.autoDay=true;this.difficulty='normal';this.assist=true;this.maskOff=false;this.customWeb=PALETTE.web;this.resting=false;this.idleTime=0;this.enemies=[];this.carried=null;this.eventClock=0;this.events=[{name:'屋顶救援',kind:'rescue',p:V(world.spawn.x-16,world.spawn.h+2.5,world.spawn.z-13),state:'ready',progress:0,need:2,story:'有人被困在停机坪附近。'}, {name:'霓虹街抢劫',kind:'robbery',p:V(0,1.6,330),state:'ready',progress:0,need:3,story:'店员的货物被抢走了。'}, {name:'消防救援',kind:'fire',p:V(-55,1.6,55),state:'ready',progress:0,need:3,story:'帮助消防队救出三位被困居民。'}, {name:'追捕无人机',kind:'chase',p:V(165,32,220),state:'ready',progress:0,need:1,story:'失控的无人机带着失窃的能源晶片。'}];this.backpacks=[world.spawn,...world.districts.slice(1).map(d=>d.b),world.shops[0].b].map((b,i)=>({p:V(b.x+12,b.h+2,b.z+10),found:false,text:['叔叔留下的旧照片：帮助别人，从身边开始。','工厂的运输记录：有人偷偷搬走能源装置。','霓虹区的笔记：电光人正在寻找新的电源。','高楼上的留言：绿魔的计划还没有结束。','店员的小纸条：谢谢你守护这座城。'][i]}));this.photos=new Set();this.race=null;this.raceBest=null;this.props=[{p:V(world.spawn.x+18,world.spawn.h+2,world.spawn.z-10),kind:'crate',weight:1},{p:V(0,1.8,315),kind:'bin',weight:1},{p:V(25,1.3,330),kind:'car',weight:3},{p:V(-55,2,315),kind:'sign',weight:2}];this.civilians=world.shops.flatMap(s=>[-1,1].map(side=>({p:V(s.door.x+side*12,0,s.door.z+4),side,react:0})));for(let i=0;i<48;i++){const x=(i%9-4)*110+(i%2?19:-19),z=(Math.floor(i/9)-2)*110+(i%3-1)*22;this.civilians.push({p:V(x,0,z),side:i%2?1:-1,react:0,name:['艾米','卢卡','小林','诺亚','贝拉','阿杰'][i%6]});}this.civilians.forEach((c,i)=>{c.home={...c.p};c.phase=i;c.line=['这条河边的日落很漂亮，你也可以在屋顶看看。','你好，蜘蛛侠！谢谢你守护我们的街区。','河岸汉堡店的薯条刚出锅，记得尝尝。','我在服装店外等朋友，要合个影吗？'][i%4];});this.events.push(...[{name:'咖啡桌的小争执',p:V(-55,1.6,318),story:'两位邻居为座位争执，可以劝和，也可以离开。'},{name:'迷路的小游客',p:V(55,1.6,316),story:'游客想找河岸餐馆，愿意帮他指路吗？'},{name:'掉落的购物袋',p:V(165,1.6,319),story:'店门口的购物袋散落了，可以帮忙收拾。'}].map(e=>({...e,kind:'conflict',state:'ready',progress:0,need:2})));this.stats={playTime:0,flightDistance:0,maxSpeed:0,websFired:0,enemiesDefeated:0,citizenTalks:0,perfectDodges:0,tricks:0};this.noLandingDistance=0;}
 dynamicSolids(actors=false){if(this.interior)return actors?Array.from({length:4},(_,i)=>({x:-17+i*8,z:13+Math.sin(this.time*.4+i),w:1.1,d:1.1,bottom:0,top:4,h:4,decoration:true,label:'店内客人'})):[];const result=super.dynamicSolids();for(const prop of this.props||[])if(!prop.used&&!prop.carried)result.push({x:prop.p.x,z:prop.p.z,w:prop.kind==='car'?5:prop.kind==='sign'?4:1.8,d:prop.kind==='car'?2.6:1.4,bottom:prop.p.y-(prop.kind==='sign'?1.4:1),top:prop.p.y+(prop.kind==='sign'?1.4:prop.kind==='car'?1.55:1),h:prop.p.y+1,decoration:true,label:'可拉拽物体',source:prop});if(actors&&this.options.citizens)for(const c of this.civilians||[])if(Math.hypot(c.p.x-this.p.x,c.p.z-this.p.z)<15)result.push({x:c.p.x,z:c.p.z,w:1,d:1,bottom:c.p.y,top:c.p.y+3.1,h:c.p.y+3.1,decoration:true,label:'市民'});return result;}

 targets(){if(!this.options.combat)return[];return [...(this.options.bossChallenge?this.world.bosses:[]),...(this.options.events?this.enemies:[])].filter(b=>!b.dead);}
 teleport(index){this.stopRest();super.teleport(index);}
 visitShop(index){this.stopRest();super.visitShop(index);}
 enterShop(shop){this.stopRest();super.enterShop(shop);}
 applyOptions(raw){return applySettings(this,raw);}
 get activeSuit(){return this.options.suitPowers?this.suitType:0;}
 updateBosses(dt){if(this.options.combat&&this.options.bossChallenge)super.updateBosses(dt);}
 selectHook(side,yaw){if(this.options.autoAttach)return super.selectHook(side,yaw);const pitch=this.aimPitch||0,view=V(-Math.sin(yaw)*Math.cos(pitch),-Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch));return this.candidates(yaw).filter(c=>dot(unit(sub(c.anchor,this.p)),view)>.94&&!firstWall(this.p,c.anchor,this.occluders())).sort((a,b)=>a.d-b.d)[0]||null;}
 attach(side,yaw,quiet=false){if(!this.options.doubleWeb&&!this.grounded&&this.airAttachCount>=1){if(!quiet)this.notify('空中二段蛛丝已关闭，落地后可以重新发射。');return false;}const ok=super.attach(side,yaw,quiet);if(ok){this.airAttachCount++;this.stats.websFired++;}return ok;}
 bindTarget(target,duration){target.bound=duration+(this.character==='miles'?1:0);target.stun=0;target.warning=0;target.charge=0;target.pullTime=0;this.burst(target.p,this.customWeb,30);this.notify('蛛丝捆住了'+target.name+' · '+target.bound.toFixed(1)+' 秒不能移动或攻击！');}
 restOnRoof(){if(this.interior||!this.grounded||this.p.y<8){this.notify('先停在安全的楼顶，再蹲下看风景。');return false;}if(this.targets().some(b=>length(sub(b.p,this.p))<40)){this.notify('这里有敌人，换个安静的屋顶休息。');return false;}this.resting=true;this.hanging=null;this.v=V();this.ropes=[null,null];return true;}
 hangFromRoof(){if(this.interior){this.notify('请先离开室内，再靠近店铺屋顶倒挂。');return false;}const b=this.world.buildings.filter(b=>Math.abs(this.p.x-b.x)<b.w/2+6&&Math.abs(this.p.z-b.z)<b.d/2+6&&this.p.y>b.h-7&&this.p.y<b.h+18).sort((a,b)=>Math.abs(this.p.y-a.h)-Math.abs(this.p.y-b.h))[0];if(!b){this.notify('先爬到屋顶或飞到屋顶附近，再点倒挂。');return false;}const candidates=[V(b.x+b.w/2+3.5,b.h-5,b.z),V(b.x-b.w/2-3.5,b.h-5,b.z),V(b.x,b.h-5,b.z+b.d/2+3.5),V(b.x,b.h-5,b.z-b.d/2-3.5)];const p=candidates.sort((a,c)=>length(sub(a,this.p))-length(sub(c,this.p)))[0];this.hanging={anchor:V(clamp(p.x,b.x-b.w/2+.3,b.x+b.w/2-.3),b.h+1.8,clamp(p.z,b.z-b.d/2+.3,b.z+b.d/2-.3)),roof:b};this.p=p;this.v=V();this.resting=false;this.climbing=null;this.grounded=false;this.ropes=[null,null];this.notify('已挂在屋檐下，转动镜头欣赏小镇。');return true;}

 stopRest(){if(this.hanging){const b=this.hanging.roof;this.p=V(b.x+b.w/2-5,b.h+2.5,b.z);this.v=V();this.grounded=true;}this.hanging=null;this.resting=false;}
 startStunts(){if(!this.options.trickChallenge){this.notify('特技评分挑战已关闭。');return false;}this.stuntChallenge={left:45,score:0};this.notify('45 秒特技挑战：飞起来，连续翻转攒分！');return true;}
 damage(n){if(!this.options.combat||this.options.damage===0)return;if(this.inv<=0){this.combo=0;this.resting=false;}super.damage(n*(this.options.damage/5)*({easy:.55,normal:1,hard:1.45}[this.difficulty]||1));}
 reward(n,message){this.style+=n;if(message)this.notify(message+' · 风格 +'+n);}
 skill(action,yaw){if(this.interior&&['boost','zip','pull','net','bind','light','heavy','trick'].includes(action)){this.notify('店里慢慢逛，技能可以出门后使用。');return false;}if((this.cooldowns[action]||0)>0){this.notify('技能正在恢复，很快就能再用。');return false;}if(['bind','net','light','heavy'].includes(action)&&!this.options.combat){this.notify('观光模式中战斗已关闭。');return false;}this.stopRest();const forward=V(-Math.sin(yaw),0,-Math.cos(yaw));
 if(action==='boost'){this.boostTime=.9;this.v=add(this.v,mul(forward,32));this.v.y=Math.max(this.v.y,this.grounded?14:4);this.grounded=false;this.cooldowns.boost=this.activeSuit===1?1.8:3;this.burst(this.p,neon,14);this.notify('蛛丝冲刺！贴墙按攀墙可以滑跑。');}
 else if(action==='zip'){const hook=this.selectHook(1,yaw);if(!hook){this.notify('朝亮起的挂点看，再试试定点弹射。');return false;}this.zipTarget=hook.anchor;this.zipTime=Math.min(.95,hook.d/(this.options.zipAssist?110:55));this.ropes=[null,null];this.v=mul(unit(sub(hook.anchor,this.p)),this.options.zipAssist?110:55);this.grounded=false;this.cooldowns.zip=2;this.stats.websFired++;this.notify('定点弹射！');}
 else if(action==='trick'){if(this.grounded||this.p.y<4){this.notify('飞到空中再做特技。');return false;}this.flip=1;this.flipKind=(this.flipKind+1)%2;this.combo=this.comboTime>0?Math.min(5,this.combo+1):1;this.comboTime=4;const points=(this.character==='gwen'?35:25)*this.combo;this.reward(points,'空中特技 ×'+this.combo);if(this.stuntChallenge)this.stuntChallenge.score+=points;if(this.options.trickSlow)this.slowTime=Math.max(this.slowTime,.45);this.cooldowns.trick=1.02;this.stats.tricks++;this.v.y+=2.5;}
 else if(action==='dodge'){const threats=this.targets().filter(b=>length(sub(b.p,this.p))<100&&!firstWall(this.p,b.p,this.occluders()));const perfect=threats.some(b=>b.warning>0&&b.warning<.4);this.inv=Math.max(this.inv,.65);this.v=add(this.v,V(Math.cos(yaw)*27,4,-Math.sin(yaw)*27));this.grounded=false;this.cooldowns.dodge=.7;if(perfect){this.slowTime=.6;this.stats.perfectDodges++;this.reward(40,'完美闪避 · 蜘蛛感应');}this.burst(this.p,PALETTE.white,8);}
 else if(action==='bind'){const target=this.targets().filter(b=>length(sub(b.p,this.p))<95&&dot(unit(sub(b.p,this.p)),forward)>-.15&&!firstWall(this.p,b.p,this.occluders())).sort((a,b)=>length(sub(a.p,this.p))-length(sub(b.p,this.p)))[0];if(!target){this.notify('朝敌人靠近一点；捆缚蛛丝不会穿过墙壁。');return false;}const start=add(this.p,V(0,.65,0));this.shots.push({p:start,v:mul(unit(sub(target.p,start)),95),life:1.4,enemy:false,r:.35,color:this.customWeb,damage:0,bindTime:this.world.bosses.includes(target)?4:target.heavy?7:12});this.cooldowns.bind=1.25;this.stats.websFired++;this.notify('捆缚蛛丝已发射！');}
 else if(action==='net'){const hits=this.targets().filter(b=>length(sub(b.p,this.p))<25&&!firstWall(this.p,b.p,this.occluders()));for(const b of hits){b.bound=(b.heavy?1.2:3)+(this.character==='miles'?1.4:0);if(this.character==='miles'){b.hp=Math.max(0,b.hp-10);if(b.hp===0){b.dead=true;this.stats.enemiesDefeated++;}}b.stun=b.bound;b.charge=0;}this.netTime=.8;this.cooldowns.net=3.5;this.notify(hits.length?'蛛丝网困住了 '+hits.length+' 个敌人！':'蛛丝网已展开，靠近敌人时更有效。');}
 else if(action==='pull'){let enemy=this.targets().filter(b=>length(sub(b.p,this.p))<90&&!firstWall(this.p,b.p,this.occluders())).sort((a,b)=>length(sub(a.p,this.p))-length(sub(b.p,this.p)))[0];const nearbyProp=this.props.filter(p=>this.options.propPull&&!p.used&&!p.carried&&length(sub(p.p,this.p))<90&&!firstWall(this.p,p.p,super.occluders(p))).sort((a,b)=>length(sub(a.p,this.p))-length(sub(b.p,this.p)))[0];if(nearbyProp&&enemy&&length(sub(nearbyProp.p,this.p))<length(sub(enemy.p,this.p))*.8)enemy=null;if(enemy){if(enemy.heavy&&this.activeSuit!==3){enemy.bound=1.3;this.notify('重甲敌人被短暂束缚，可接重击。');}else{const end=add(this.p,mul(unit(sub(enemy.p,this.p)),6));if(!firstWall(enemy.p,end,this.occluders()))enemy.pullTarget=end;enemy.pullTime=.3;enemy.bound=2;this.notify('拉住敌人！接轻击或重击。');}this.cooldowns.pull=2;}
 else{if(!this.options.propPull){this.notify('环境物体拉拽已关闭，仍可拉拽敌人。');return false;}const prop=this.props.filter(p=>!p.used&&!p.carried&&length(sub(p.p,this.p))<90&&!firstWall(this.p,p.p,super.occluders(p))).sort((a,b)=>length(sub(a.p,this.p))-length(sub(b.p,this.p)))[0];if(!prop){this.notify('朝箱子、垃圾桶、广告牌或车辆靠近一点。');return false;}if(prop.weight>2&&this.activeSuit!==3){this.notify('汽车很重，力量装甲战衣才能拉动。');return false;}this.carried=prop;prop.carried=true;this.cooldowns.pull=2;this.notify('拉住了！按攻击把它抛向敌人。');}}
 else if(action==='light'||action==='heavy'){const heavy=action==='heavy',target=this.targets().filter(b=>length(sub(b.p,this.p))<(heavy?8:6)&&!firstWall(this.p,b.p,this.occluders())).sort((a,b)=>length(sub(a.p,this.p))-length(sub(b.p,this.p)))[0];if(!target){this.notify('近身攻击需要靠近敌人，或先用拉拽。');return false;}this.combo=this.comboTime>0?Math.min(5,this.combo+1):1;this.comboTime=3;let damage=heavy?38:16;if(target.heavy&&!heavy&&!target.bound)damage*=.35;target.hp=Math.max(0,target.hp-damage);target.stun=heavy?.8:.15;if(!this.grounded)target.p.y+=heavy?2:.4;if(target.hp===0){target.dead=true;this.stats.enemiesDefeated++;this.reward(25,'连招击败'+target.name);}this.v.y=Math.max(this.v.y,this.grounded?0:4);this.burst(target.p,heavy?orange:neon,14);this.cooldowns[action]=heavy?.65:.22;}
 else return false;return true;}
 attack(){if(!this.options.combat)return;if(this.carried&&this.attackCool<=0){const prop=this.carried,target=this.targets().filter(b=>length(sub(b.p,this.p))<150&&!firstWall(this.p,b.p,this.occluders())).sort((a,b)=>length(sub(a.p,this.p))-length(sub(b.p,this.p)))[0],direction=target?unit(sub(target.p,this.p)):V(-Math.sin(this.facing),.05,-Math.cos(this.facing));this.shots.push({p:add(this.p,V(0,1,0)),v:mul(direction,65),r:prop.kind==='car'?1.5:.8,color:orange,kind:prop.kind,life:3,enemy:false,damage:this.activeSuit===3?85:60});prop.used=true;prop.carried=false;this.carried=null;this.attackCool=.4;this.notify('环境投掷！');return;}const cool=this.attackCool;super.attack();if(cool<=0)this.stats.websFired++;}
 updateClimb(input,yaw){if(this.options.autoClimb&&!this.interior&&!this.ropes.some(Boolean))input={...input,climb:true};if(this.interior&&input.climb&&(this.ceilingCrawl||this.p.y>=10)){this.ceilingCrawl=true;this.climbing={b:{h:12},normal:V(0,-1,0),ceiling:true};this.p.y=10.2;this.v=add(mul(V(-Math.sin(yaw),0,-Math.cos(yaw)),(input.forward||0)*7),mul(V(Math.cos(yaw),0,-Math.sin(yaw)),(input.right||0)*7));return;}this.ceilingCrawl=false;super.updateClimb(input,yaw);if(this.climbing&&this.boostTime>0){const n=this.climbing.normal,t=V(n.z,0,-n.x);this.v=add(mul(t,(input.right||1)*16),V(0,(input.forward||0)*7,0));}}
 shopAction(action){if(this.interior?.shop.type===1){if(action===5){if(!(this.achievements&&this.achievements.complete)){this.notify('达成全部成就后，这件战衣会为你点亮。');return;}this.suitType=5;this.suit={red:color('#2b2d42'),blue:color('#c9a227')};this.notify('午夜鎏金：属于城市传奇的专属战衣。');return;}if(!this.options.unlockSuits&&(action===3&&this.style<120||action===4&&this.style<300)){this.notify('多做特技和城市事件，攒风格分数解锁这套战衣。');return;}this.suitType=action;if(action>=3){this.suit=action===3?{red:color('#df6338'),blue:color('#344154')}:{red:color('#d6e8fa'),blue:color('#306ab4')};this.notify(action===3?'力量装甲：可以拉动汽车，环境投掷威力提升。':'星耀战衣：特技持续时间更长，发光轨迹已解锁。');return;}super.shopAction(action);this.notify(['经典战衣：平衡的移动与战斗。','极光战衣：冲刺恢复速度更快。','夜行战衣：敌人更难注意到你。'][action]);return;}super.shopAction(action);}
 nearbyActivity(){return this.backpacks.find(b=>!b.found&&length(sub(b.p,this.p))<6)||(this.options.events&&this.events.find(e=>e.state!=='done'&&length(sub(e.p,this.p))<13))||(this.options.citizens&&this.civilians.find(c=>length(sub(add(c.p,V(0,1.6,0)),this.p))<7))||null;}
 interactActivity(){const backpack=this.backpacks.find(b=>!b.found&&length(sub(b.p,this.p))<6);if(backpack){backpack.found=true;this.reward(45,'找到旧背包');this.notify(backpack.text);return true;}const event=this.options.events&&this.events.find(e=>e.state!=='done'&&length(sub(e.p,this.p))<13);if(!event){const citizen=this.options.citizens&&this.civilians.find(c=>length(sub(add(c.p,V(0,1.6,0)),this.p))<7);if(!citizen)return false;citizen.react=5;this.stats.citizenTalks++;this.notify((citizen.name||'邻居')+'：'+citizen.line);return true;}if(event.kind==='rescue'||event.kind==='fire'||event.kind==='conflict'){event.state='active';event.progress++;this.burst(event.p,neon,10);if(event.progress>=event.need)this.finishEvent(event);else this.notify(event.kind==='conflict'?'听完邻居的意见，再按互动帮他们解决。':'蛛丝救出一位居民 · '+event.progress+' / '+event.need);}else{this.activateEvent(event);this.notify(event.kind==='chase'?'用蛛丝追上无人机，拉拽、捆缚后攻击。':'先制住抢劫者，重甲敌人用重击或环境投掷。');}return true;}
 activateEvent(event){if(!this.options.events||!this.options.combat||!this.options.enemySpawn){this.notify('事件敌人刷新已关闭，可以自由逛街。');return;}if(event.state!=='ready')return;event.state='active';if(event.kind==='robbery'||event.kind==='chase'){const types=event.kind==='chase'?['fly']:['thug','armor','sniper'];for(let i=0;i<types.length;i++){const type=types[i],p=add(event.p,V((i-1)*8,type==='fly'?3:0,-7));this.enemies.push({p,name:{thug:'打手',armor:'重甲卫兵',sniper:'狙击手',fly:'飞行无人机'}[type],enemyType:type,heavy:type==='armor',hp:type==='armor'?140:70,max:type==='armor'?140:70,dead:false,stun:0,bound:0,warning:0,cool:1.5+i,time:0,color:type==='fly'?neon:orange,event});}}}
 finishEvent(event){if(event.state==='done')return;event.state='done';this.reward(90,'完成'+event.name);this.hp=Math.min(100,this.hp+25);}
 startRace(){if(!this.options.race){this.notify('竞速挑战已关闭。');return false;}this.stopRest();this.teleport(0);const nearest=(i,j)=>this.world.buildings.reduce((a,b)=>Math.hypot(b.i-i,b.j-j)<Math.hypot(a.i-i,a.j-j)?b:a);const bs=[this.world.spawn,this.world.buildings.find(b=>b.i===0&&b.j===2),nearest(1,1),this.world.districts[1].b,nearest(2,-1),this.world.districts[3].b,this.world.districts[2].b,this.world.spawn];this.race={points:bs.map(b=>V(b.x,b.h+8,b.z)),index:0,time:0};this.notify('摆荡计时开始！穿过蓝色光环，试试把冲刺与弹射接起来。');}
 update(dt,input,yaw){if(this.grounded)this.airAttachCount=0;this.stats.playTime+=dt;this.weatherClock+=dt;if(this.options.randomWeather&&this.weatherClock>75){this.weatherClock=0;this.weather=['clear','rain','fog'][(Math.floor(this.time/75)+1)%3];}if(this.autoDay)this.dayTime=(this.dayTime+dt/600)%1;if(this.stuntChallenge){this.stuntChallenge.left-=dt;if(this.stuntChallenge.left<=0){this.notify('特技挑战结束 · '+this.stuntChallenge.score+' 分');this.stuntChallenge=null;}}this.citizenClock=(this.citizenClock||0)+dt;if(this.options.citizens&&this.citizenClock>=.2){const elapsed=this.citizenClock;this.citizenClock=0;const nearbySolids=this.interior?this.interior.collision:this.world.collision;for(const c of this.civilians){c.react=Math.max(0,c.react-elapsed);if(c.react||Math.hypot(c.p.x-this.p.x,c.p.z-this.p.z)>130)continue;const next=V(c.home.x,c.home.y,c.home.z+Math.sin(this.time*.14+c.phase)*8);if(!firstWall(add(c.p,V(0,1.6,0)),add(next,V(0,1.6,0)),nearbySolids))c.p=next;}}if(this.resting||this.hanging){if(input.forward||input.right||input.jump||input.climb||input.attack)this.stopRest();else{this.time+=dt;this.idleTime+=dt;if(this.resting)this.hp=Math.min(100,this.hp+12*dt);return;}}for(const key in this.cooldowns)this.cooldowns[key]=Math.max(0,this.cooldowns[key]-dt);for(const key of ['flip','boostTime','zipTime','slowTime','netTime','comboTime'])this[key]=Math.max(0,this[key]-dt);if(this.zipTime>0&&this.zipTarget){const delta=sub(this.zipTarget,this.p);if(length(delta)<5){this.zipTime=0;this.v.y=12;}else this.v=mul(unit(delta),this.options.zipAssist?110:55);}if(input.forward||input.right||input.jump||input.climb||input.attack){this.resting=false;this.idleTime=0;}else this.idleTime+=dt;
 for(const target of this.targets())if(target.pullTime>0){target.pullTime=Math.max(0,target.pullTime-dt);const next=add(target.p,mul(sub(target.pullTarget,target.p),1-Math.exp(-18*dt)));if(!firstWall(target.p,next,super.occluders()))target.p=next;}const wasGrounded=this.grounded,airPos={...this.p};super.update(dt,input,yaw);updateHeroPose(this,dt);const airStep=length(sub(this.p,airPos));if(this.grounded)this.noLandingDistance=0;else if(airStep<=50){this.stats.flightDistance+=airStep;this.noLandingDistance+=airStep;}if(Math.hypot(this.v.x,this.v.z)>this.stats.maxSpeed)this.stats.maxSpeed=Math.hypot(this.v.x,this.v.z);if(wasGrounded&&input.jump&&this.character==='gwen'&&this.v.y>0)this.v.y*=1.12;if(this.weather==='rain'&&!this.grounded){this.v.x*=Math.exp(.03*dt);this.v.z*=Math.exp(.03*dt);}if(this.resting&&this.grounded)this.hp=Math.min(100,this.hp+12*dt);if(this.interior)return;
 for(const event of this.options.events?this.events:[]){if(event.state==='ready'&&this.options.combat&&this.options.enemySpawn&&length(sub(event.p,this.p))<90&&['robbery','chase'].includes(event.kind)){this.activateEvent(event);this.notify('城市事件：'+event.name+' · 可以自由选择是否参与。');}if(event.state==='active'&&['robbery','chase'].includes(event.kind)){const alive=this.enemies.filter(b=>b.event===event&&!b.dead);event.progress=event.need-alive.length;if(!alive.length)this.finishEvent(event);}}
 for(const enemy of this.options.combat&&this.options.events?this.enemies:[]){if(enemy.dead)continue;enemy.time+=dt;enemy.bound=Math.max(0,enemy.bound-dt);enemy.stun=Math.max(0,enemy.stun-dt);if(enemy.bound||enemy.stun)continue;const d=sub(this.p,enemy.p),dist=length(d);if(dist>(this.activeSuit===2?90:150)||firstWall(enemy.p,this.p,this.occluders()))continue;const fly=enemy.enemyType==='fly';if(fly)enemy.p.y=enemy.event.p.y+4+Math.sin(enemy.time*2)*2;const speed=enemy.heavy?4:enemy.enemyType==='sniper'?0:fly?10:8;if(dist>6&&speed){const next=add(enemy.p,mul(unit(V(d.x,0,d.z)),speed*dt));if(!firstWall(enemy.p,next,this.occluders(),.75))enemy.p=next;}if(enemy.warning>0){enemy.warning-=dt;if(enemy.warning<=0){this.shots.push({p:add(enemy.p,V(0,.7,0)),v:mul(unit(sub(this.p,enemy.p)),enemy.enemyType==='sniper'?80:30),r:.4,life:4,enemy:true,color:orange,damage:enemy.heavy?20:12});enemy.cool=enemy.enemyType==='sniper'?3.2:2.5;}}else{enemy.cool-=dt;if(enemy.cool<=0)enemy.warning=enemy.enemyType==='sniper'?1:.65;}}
 if(this.race){this.race.time+=dt;if(length(sub(this.p,this.race.points[this.race.index]))<13){this.race.index++;if(this.race.index===this.race.points.length){const time=this.race.time;this.raceBest=this.raceBest===null?time:Math.min(time,this.raceBest);this.reward(120,'完成摆荡赛道：'+time.toFixed(1)+' 秒');this.race=null;}else this.notify('通过光环 '+this.race.index+' / 8');}}
 }
 get environment(){const light=Math.max(0,Math.sin(this.dayTime*Math.PI*2)),sky=[.025+light*.24,.055+light*.34,.12+light*.4];return{sky,ambient:.48+light*.2,fogNear:this.weather==='fog'?70:170,fogFar:this.weather==='fog'?270:640,phase:Math.floor(this.dayTime*24)+'-'+this.weather};}
 get sense(){if(this.interior||!this.options.sense)return'';const target=this.targets().find(b=>b.warning>0&&length(sub(b.p,this.p))<130&&!firstWall(this.p,b.p,this.occluders()));return target?'蜘蛛感应！按闪避，临近命中可触发慢动作。':this.race?'摆荡计时 '+(this.race.index+1)+' / 8 · '+this.race.time.toFixed(1)+'秒':'';}
}
export function makePlayer(g,sim){const body=new Geometry();makeHero(body,sim);const speed=Math.hypot(sim.v.x,sim.v.z),yaw=sim.facing,forward=V(-Math.sin(yaw),0,-Math.cos(yaw)),right=V(Math.cos(yaw),0,-Math.sin(yaw));const pose=heroPose(sim),pitch=pose.pitch,roll=pose.roll;const cp=Math.cos(pitch),sp=Math.sin(pitch),cr=Math.cos(roll),sr=Math.sin(roll),co=Math.cos(yaw),si=Math.sin(yaw);const rotate=(x,y,z)=>{const xx=x*co-z*si,zz=x*si+z*co,py=y*cp-zz*sp,pz=y*sp+zz*cp,px=xx*cr-py*sr,yy=xx*sr+py*cr;return [px*co+pz*si,yy,-px*si+pz*co];};for(let i=0;i<body.data.length;i+=9){const d=body.data,p=rotate(d[i]-sim.p.x,d[i+1]-sim.p.y,d[i+2]-sim.p.z),n=rotate(d[i+3],d[i+4],d[i+5]);g.data.push(p[0]+sim.p.x,p[1]+sim.p.y,p[2]+sim.p.z,n[0],n[1],n[2],d[i+6],d[i+7],d[i+8]);}
 sim.renderHands=(sim.modelHands||[]).map(h=>{const p=rotate(h.x-sim.p.x,h.y-sim.p.y,h.z-sim.p.z);return V(p[0]+sim.p.x,p[1]+sim.p.y,p[2]+sim.p.z);});if(sim.grounded&&!sim.hanging)g.sphere(sim.p.x,sim.p.y-1.585,sim.p.z,.7,color('#727d80'),1,.015,.65,14,3);
 if(sim.activeSuit===4&&speed>25)for(let i=1;i<5;i++){const p=sub(sim.p,mul(unit(sim.v),i*.9));g.sphere(p.x,p.y,p.z,.1,neon);}
}
function person(g,p,c,yaw=0,phone=false,time=0){const skin=color('#d1a080'),dark=color('#344457'),step=phone?0:Math.sin(time*2.5+p.x)*.16;g.sphere(p.x,p.y+1.55,p.z,.48,c,.88,1.22,.57,10,7);g.limb(add(p,V(0,1.9,0)),add(p,V(0,2.18,0)),.16,skin);g.sphere(p.x,p.y+2.45,p.z,.39,skin,.91,1.12,.9,12,8);g.sphere(p.x,p.y+2.67,p.z+.025,.4,color('#4b3c36'),1,.55,1,10,6);g.sphere(p.x,p.y+2.4,p.z-.35,.07,skin,1,.9,1,6,4);for(const side of [-1,1]){g.sphere(p.x+side*.14,p.y+2.52,p.z-.325,.028,dark,1,1,.5,6,3);const knee=add(p,V(side*.19,.68,side*step)),foot=add(p,V(side*.21,.13,side*step*.7-.08));g.limb(add(p,V(side*.18,1.22,0)),knee,.15,dark);g.limb(knee,foot,.14,dark);g.sphere(foot.x,foot.y,foot.z,.19,color('#575854'),1,.6,1.4,8,4);const elbow=add(p,V(side*.52,1.58,-side*step)),hand=add(p,V(side*.55,phone?2.15:1.2,phone?-.35:-side*step));g.limb(add(p,V(side*.37,1.93,0)),elbow,.13,c);g.limb(elbow,hand,.1,c);g.sphere(hand.x,hand.y,hand.z,.13,skin,1,1,1,8,4);if(phone&&side===1)g.box(hand.x,hand.y,hand.z-.08,.18,.3,.07,color('#97c2c7'));}g.box(p.x,p.y+1.05,p.z-.24,.5,.05,.04,color('#bba891'));}
export function makeAdventure(g,sim){if(sim.hanging)g.limb(sim.hanging.anchor,add(sim.p,V(0,1.4,0)),.05,sim.customWeb);if(sim.interior){if(sim.options.citizens)for(let i=0;i<4;i++)person(g,V(-17+i*8,0,13+Math.sin(sim.time*.4+i)),color(i%2?'#c990ad':'#7daaaa'),0,true,sim.time);return;}for(const prop of sim.props){if(prop.used)continue;const p=prop.carried?add(sim.p,V(0,1.5,-2)):prop.p;if(length(sub(p,sim.p))>200)continue;if(prop.kind==='car'){g.box(p.x,p.y,p.z,5,1.8,2.6,color('#455f87'));g.box(p.x,p.y+1.1,p.z,2.6,.9,2.2,color('#347389'));for(const s of [-1,1])for(const z of [-1,1])g.sphere(p.x+s*1.7,p.y-.65,p.z+z*1.2,.5,PALETTE.ink);}else{g.box(p.x,p.y,p.z,prop.kind==='sign'?4:1.8,prop.kind==='sign'?2.8:2,1.4,color('#49657e'));g.box(p.x,p.y+.3,p.z-.74,1.4,.15,.04,neon);}}
 for(const c of sim.options.citizens?sim.civilians.filter(c=>Math.hypot(c.p.x-sim.p.x,c.p.z-sim.p.z)<100).sort((a,b)=>length(sub(a.p,sim.p))-length(sub(b.p,sim.p))).slice(0,18):[]){person(g,c.p,color(c.side>0?'#367b89':'#9b628c'),0,length(sub(c.p,sim.p))<30,sim.time);}
 for(const e of sim.options.events?sim.events:[]){if(e.state==='done'||length(sub(e.p,sim.p))>220)continue;if(e.kind==='rescue'||e.kind==='fire'||e.kind==='conflict'){for(let i=e.progress;i<e.need;i++)person(g,add(e.p,V((i-1)*4,e.kind==='rescue'?-1.6:0,3)),color('#cf8f66'));}if(e.kind==='fire'){for(let i=0;i<4;i++){const y=2+Math.sin(sim.time*7+i)*.8;g.sphere(e.p.x+(i-1.5)*2,e.p.y+y,e.p.z-3,1.5,orange,.7,1.7,.7);g.sphere(e.p.x+(i-1.5)*2,e.p.y+y+2,e.p.z-3,1.2,color('#4c5464'));}}}
 for(const b of sim.backpacks)if(!b.found&&length(sub(b.p,sim.p))<150){g.box(b.p.x,b.p.y,b.p.z,1.2,1.7,.65,color('#ba6c47'));g.box(b.p.x,b.p.y+.2,b.p.z-.4,.8,.7,.2,neon);}
 for(const b of sim.options.combat&&sim.options.events?sim.enemies:[]){if(b.dead||length(sub(b.p,sim.p))>200)continue;const p=b.p;if(b.enemyType==='fly'){g.sphere(p.x,p.y,p.z,1.1,color('#4b657b'),1,.7,1);for(const s of [-1,1])g.box(p.x+s*1.7,p.y,p.z,1.9,.15,.5,neon);}else{person(g,add(p,V(0,-1.6,0)),color(b.heavy?'#637086':'#a05955'));if(b.heavy){g.box(p.x,p.y+.2,p.z,1.45,1.6,.8,color('#3b4c62'));g.box(p.x,p.y+.4,p.z-.5,.8,.17,.05,orange);}if(b.enemyType==='sniper')g.limb(add(p,V(.6,.5,-.2)),add(p,V(.6,.5,-1.4)),.12,PALETTE.ink);}if(b.bound>0)webCocoon(g,p,b.heavy?1.3:1,sim.customWeb);if(b.warning>0&&sim.options.sense)g.cone(p.x,p.y+3,p.z,.4,1,[2,.25,.2]);}
 for(const target of sim.targets()){if(target.pullTime>0)g.limb(add(sim.p,V(0,.5,0)),target.p,.045,sim.customWeb);if(target.bound>0&&sim.world.bosses.includes(target))webCocoon(g,target.p,2.2,sim.customWeb);}if(sim.netTime>0)for(let i=0;i<12;i++){const a=i/12*Math.PI*2;g.limb(sim.p,add(sim.p,V(Math.cos(a)*12,.2,Math.sin(a)*12)),.04,sim.customWeb);}
 if(sim.race){const p=sim.race.points[sim.race.index];for(let i=0;i<20;i++){const a=i/20*Math.PI*2,b=(i+1)/20*Math.PI*2;g.limb(add(p,V(Math.cos(a)*11,Math.sin(a)*11,0)),add(p,V(Math.cos(b)*11,Math.sin(b)*11,0)),.18,neon);}}
}

function webCocoon(g,p,r,c){for(let y=-1.5;y<=1.5;y+=.35)for(let i=0;i<10;i++){const a=i/10*Math.PI*2,b=(i+1)/10*Math.PI*2;g.limb(add(p,V(Math.cos(a)*r,y,Math.sin(a)*r*.7)),add(p,V(Math.cos(b)*r,y,Math.sin(b)*r*.7)),.065,c);if(y<1.5)g.limb(add(p,V(Math.cos(a)*r,y,Math.sin(a)*r*.7)),add(p,V(Math.cos(b)*r,y+.5,Math.sin(b)*r*.7)),.028,c);}}
