import {Geometry,V,add,sub,mul,dot,length,unit,clamp} from './engine3d.js?v=20261006savefix';
// Spatial bins are shared by movement, projectiles and camera queries.
export class CollisionIndex {
 constructor(items){this.items=items;this.bins=new Map();for(const b of items){for(let x=Math.floor((b.x-b.w/2)/32);x<=Math.floor((b.x+b.w/2)/32);x++)for(let z=Math.floor((b.z-b.d/2)/32);z<=Math.floor((b.z+b.d/2)/32);z++){const key=x+','+z;if(!this.bins.has(key))this.bins.set(key,[]);this.bins.get(key).push(b);}}}
 [Symbol.iterator](){return this.items[Symbol.iterator]();}
 queryBox(a,b,pad=0){const result=new Set();for(let x=Math.floor((Math.min(a.x,b.x)-pad)/32);x<=Math.floor((Math.max(a.x,b.x)+pad)/32);x++)for(let z=Math.floor((Math.min(a.z,b.z)-pad)/32);z<=Math.floor((Math.max(a.z,b.z)+pad)/32);z++)for(const item of this.bins.get(x+','+z)||[])result.add(item);return result;}
}
export class CollisionScene {
 constructor(index,extras=[]){this.index=index;this.extras=extras;}
 *[Symbol.iterator](){yield* this.index;yield* this.extras;}
 queryBox(a,b,pad=0){return [...queryCollisions(this.index,a,b,pad),...this.extras];}
}
export function queryCollisions(items,a,b,pad=0){return items.queryBox?items.queryBox(a,b,pad):items;}
// Record the exact primitive alongside its mesh, avoiding unregistered decorations.
export class SolidGeometry extends Geometry {
 constructor(){super();this.colliders=[];this.collisionLabel=null;}
 capture(label,draw){const old=this.collisionLabel;this.collisionLabel=label;draw();this.collisionLabel=old;}
 record(b){if(this.collisionLabel)this.colliders.push({...b,decoration:true,label:this.collisionLabel,h:b.top});}
 box(x,y,z,w,h,d,c,yaw=0){super.box(x,y,z,w,h,d,c,yaw);if(h<.08||Math.min(w,d)<.065||y+h/2<.12)return;this.record({x,z,w:Math.abs(Math.cos(yaw))*w+Math.abs(Math.sin(yaw))*d,d:Math.abs(Math.cos(yaw))*d+Math.abs(Math.sin(yaw))*w,bottom:y-h/2,top:y+h/2,shape:'box',width:w,depth:d,yaw});}
 sphere(x,y,z,r,c,rx=1,ry=1,rz=1,sides=12,rings=8){super.sphere(x,y,z,r,c,rx,ry,rz,sides,rings);if(r<.45||r*ry<.14)return;this.record({shape:'ellipsoid',x,z,y,rx:r*rx,ry:r*ry,rz:r*rz,w:r*rx*2,d:r*rz*2,bottom:y-r*ry,top:y+r*ry});}
 limb(a,b,r,c){super.limb(a,b,r,c);if(r<.065)return;this.record({shape:'capsule',a,b,r,x:(a.x+b.x)/2,z:(a.z+b.z)/2,w:Math.abs(a.x-b.x)+2*r,d:Math.abs(a.z-b.z)+2*r,bottom:Math.min(a.y,b.y)-r,top:Math.max(a.y,b.y)+r});}
 cone(x,y,z,r,h,c){super.cone(x,y,z,r,h,c);if(r>.4)this.record({shape:'ellipsoid',x,z,y:y+h/2,rx:r,ry:h/2,rz:r,w:2*r,d:2*r,bottom:y,top:y+h});}
}
function boxHit(a,b,wall,pad=0,body=false){const co=Math.cos(wall.yaw||0),si=Math.sin(wall.yaw||0),local=p=>V((p.x-wall.x)*co-(p.z-wall.z)*si,p.y,(p.x-wall.x)*si+(p.z-wall.z)*co);const A=local(a),B=local(b),D=sub(B,A),lo=V(-(wall.width??wall.w)/2-pad,(wall.bottom??0)-(body?1.85:pad),-(wall.depth??wall.d)/2-pad),hi=V((wall.width??wall.w)/2+pad,(wall.top??wall.h+.9)+(body?1.6:pad),(wall.depth??wall.d)/2+pad);let entry=0,exit=1,normal=V(),inside=true,depth=Infinity,nearest=V();for(const axis of ['x','y','z']){if(A[axis]<lo[axis]-1e-5||A[axis]>hi[axis]+1e-5)inside=false;const dl=A[axis]-lo[axis],dh=hi[axis]-A[axis];if(dl<depth){depth=dl;nearest=V();nearest[axis]=-1;}if(dh<depth){depth=dh;nearest=V();nearest[axis]=1;}if(Math.abs(D[axis])<1e-10){if(A[axis]<lo[axis]||A[axis]>hi[axis])return null;}else{let t1=(lo[axis]-A[axis])/D[axis],t2=(hi[axis]-A[axis])/D[axis],sign=-1;if(t1>t2){[t1,t2]=[t2,t1];sign=1;}if(t1>entry){entry=t1;normal=V();normal[axis]=sign;}exit=Math.min(exit,t2);if(entry>exit)return null;}}if(inside){normal=nearest;if(body&&depth<=.003&&dot(D,normal)>=-1e-8)return null;entry=0;}const n=V(normal.x*co+normal.z*si,normal.y,-normal.x*si+normal.z*co);return{t:entry,normal:n,penetration:inside?Math.max(0,depth):0,wall};}
function sphereHit(a,b,center,rx,ry,rz,body=false){const A=V((a.x-center.x)/rx,(a.y-center.y)/ry,(a.z-center.z)/rz),D=V((b.x-a.x)/rx,(b.y-a.y)/ry,(b.z-a.z)/rz),C=dot(A,A)-1,Q=dot(D,D),L=dot(A,D),disc=L*L-Q*C;if(Q<1e-12||disc<0)return null;let t=C<=0?0:(-L-Math.sqrt(disc))/Q;if(t<0||t>1)return null;const P=add(A,mul(D,t)),normal=unit(V(P.x/rx,P.y/ry,P.z/rz));if(body&&C>-0.004&&dot(sub(b,a),normal)>=-1e-8)return null;return{t,normal,penetration:C<0?(1-Math.sqrt(dot(A,A)))*Math.min(rx,ry,rz):0};}
function capsuleHit(a,b,wall,pad,body){const start=wall.a,end=wall.b,axis=sub(end,start),ll=dot(axis,axis),r=wall.r+pad;if(ll<1e-9)return sphereHit(a,b,start,r,r,r,body);const D=sub(b,a),M=sub(a,start),h=dot(M,axis)/ll,k=dot(D,axis)/ll,perp=sub(M,mul(axis,h)),d=sub(D,mul(axis,k)),A=dot(d,d),B=dot(perp,d),C=dot(perp,perp)-r*r;let best=null;const accept=t=>{if(t<0||t>1)return;const q=h+k*t;if(q<0||q>1)return;const n=unit(add(perp,mul(d,t)));if(body&&C>-.004&&dot(D,n)>=0)return;best={t,normal:n,penetration:t===0?Math.max(0,r-length(perp)):0};};if(C<=0&&h>=0&&h<=1)accept(0);else if(A>1e-12){const disc=B*B-A*C;if(disc>=0)accept((-B-Math.sqrt(disc))/A);}for(const p of [start,end]){const hit=sphereHit(a,b,p,r,r,r,body);if(hit&&(!best||hit.t<best.t))best=hit;}return best;}
export function segmentHit(a,b,wall,pad=0,body=false){if(wall.shape==='ellipsoid'){const hit=sphereHit(a,b,V(wall.x,wall.y,wall.z),wall.rx+pad,wall.ry+(body?1.6:pad),wall.rz+pad,body);return hit?{...hit,wall}:null;}if(wall.shape==='capsule'){let best=null;for(const offset of body?[-.65,0,.65]:[0]){const hit=capsuleHit(add(a,V(0,offset,0)),add(b,V(0,offset,0)),wall,pad,body);if(hit&&(!best||hit.t<best.t))best={...hit,wall};}return best;}return boxHit(a,b,wall,pad,body);}
export function nearestCollision(a,b,items,pad=0,body=false){let best=null;for(const wall of queryCollisions(items,a,b,pad+2)){const verticalPad=body?1.85:pad;if(Math.max(a.y,b.y)+verticalPad<(wall.bottom??0)||Math.min(a.y,b.y)-verticalPad>(wall.top??wall.h+.9))continue;if(Math.max(a.x,b.x)+pad<wall.x-wall.w/2||Math.min(a.x,b.x)-pad>wall.x+wall.w/2||Math.max(a.z,b.z)+pad<wall.z-wall.d/2||Math.min(a.z,b.z)-pad>wall.z+wall.d/2)continue;const hit=segmentHit(a,b,wall,pad,body);if(hit&&(!best||hit.t<best.t||(hit.t===best.t&&hit.penetration>best.penetration)))best=hit;}return best;}
export function moveSolid(start,end,velocity,items,canStep=false){let p={...start},remaining=sub(end,start),v={...velocity},ground=null;for(let pass=0;pass<6;pass++){if(length(remaining)<1e-9&&pass>0)break;const hit=nearestCollision(p,add(p,remaining),items,1.1,true);if(!hit){p=add(p,remaining);break;}const n=hit.normal;if(canStep&&Math.abs(n.y)<.2&&(hit.wall.top??hit.wall.h+.9)<=p.y-1.6+.55&&v.y<=0){p.y=(hit.wall.top??hit.wall.h+.9)+1.603;ground=hit.wall;continue;}if(length(n)<.1)break;p=add(p,mul(remaining,Math.max(0,hit.t-.00001)));p=add(p,mul(n,Math.min(hit.penetration||0,4)+.003));remaining=mul(remaining,1-hit.t);const into=dot(remaining,n);if(into<0)remaining=sub(remaining,mul(n,into));const speed=dot(v,n);if(speed<0)v=sub(v,mul(n,speed));if(n.y>.55)ground=hit.wall;}
 return{p,v,ground};}
