// Small WebGL renderer: lit meshes, atmospheric fog and a movable 3D camera.
export const V=(x=0,y=0,z=0)=>({x,y,z});
export const add=(a,b)=>V(a.x+b.x,a.y+b.y,a.z+b.z);
export const sub=(a,b)=>V(a.x-b.x,a.y-b.y,a.z-b.z);
export const mul=(a,k)=>V(a.x*k,a.y*k,a.z*k);
export const dot=(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z;
export const length=a=>Math.hypot(a.x,a.y,a.z);
export const unit=a=>mul(a,1/(length(a)||1));
export const cross=(a,b)=>V(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x);
export const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export const mix=(a,b,t)=>add(a,mul(sub(b,a),t));
export const color=h=>{h=h.replace('#','');return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255];};
export function multiply(a,b){const out=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)out[c*4+r]+=a[k*4+r]*b[c*4+k];return out;}
export function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),r=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(near+far)*r,-1,0,0,2*near*far*r,0]);}
export function lookAt(eye,target){const z=unit(sub(eye,target)),x=unit(cross(V(0,1,0),z)),y=cross(z,x);return new Float32Array([x.x,y.x,z.x,0,x.y,y.y,z.y,0,x.z,y.z,z.z,0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
export class Geometry {
 constructor(){this.data=[];}
 triangle(a,b,c,n,col){for(const p of [a,b,c])this.data.push(p.x,p.y,p.z,n.x,n.y,n.z,...col);}
 quad(a,b,c,d,n,col){this.triangle(a,b,c,n,col);this.triangle(a,c,d,n,col);}
 box(x,y,z,w,h,d,col,yaw=0){const co=Math.cos(yaw),si=Math.sin(yaw);const point=(a,b,c)=>V(x+a*co+c*si,y+b,z-a*si+c*co);const normal=(a,b,c)=>V(a*co+c*si,b,-a*si+c*co);const X=w/2,Y=h/2,Z=d/2;
 this.quad(point(-X,-Y,Z),point(X,-Y,Z),point(X,Y,Z),point(-X,Y,Z),normal(0,0,1),col);
 this.quad(point(X,-Y,-Z),point(-X,-Y,-Z),point(-X,Y,-Z),point(X,Y,-Z),normal(0,0,-1),col);
 this.quad(point(X,-Y,Z),point(X,-Y,-Z),point(X,Y,-Z),point(X,Y,Z),normal(1,0,0),col);
 this.quad(point(-X,-Y,-Z),point(-X,-Y,Z),point(-X,Y,Z),point(-X,Y,-Z),normal(-1,0,0),col);
 this.quad(point(-X,Y,Z),point(X,Y,Z),point(X,Y,-Z),point(-X,Y,-Z),V(0,1,0),col);
 this.quad(point(-X,-Y,-Z),point(X,-Y,-Z),point(X,-Y,Z),point(-X,-Y,Z),V(0,-1,0),col);}
 sphere(x,y,z,r,col,rx=1,ry=1,rz=1,sides=12,rings=8){const p=(j,i)=>{const a=j/rings*Math.PI,b=i/sides*Math.PI*2;return V(x+Math.sin(a)*Math.cos(b)*r*rx,y+Math.cos(a)*r*ry,z+Math.sin(a)*Math.sin(b)*r*rz);};for(let j=0;j<rings;j++)for(let i=0;i<sides;i++){const a=p(j,i),b=p(j+1,i),c=p(j+1,i+1),d=p(j,i+1),n=unit(sub(mul(add(add(a,b),c),1/3),V(x,y,z)));this.quad(a,b,c,d,n,col);}}
 limb(a,b,r,col){const axis=unit(sub(b,a)),right=unit(cross(axis,Math.abs(axis.y)>.9?V(1,0,0):V(0,1,0))),front=cross(axis,right);const p=(base,angle)=>add(base,add(mul(right,Math.cos(angle)*r),mul(front,Math.sin(angle)*r)));for(let i=0;i<6;i++){const an=i/6*Math.PI*2,next=(i+1)/6*Math.PI*2;this.quad(p(a,an),p(b,an),p(b,next),p(a,next),unit(add(mul(right,Math.cos((an+next)/2)),mul(front,Math.sin((an+next)/2)))),col);}}
 spike(a,b,r,col){const axis=unit(sub(b,a)),right=unit(cross(axis,Math.abs(axis.y)>.9?V(1,0,0):V(0,1,0))),front=cross(axis,right);for(let i=0;i<10;i++){const an=i/10*Math.PI*2,next=(i+1)/10*Math.PI*2,p=add(a,add(mul(right,Math.cos(an)*r),mul(front,Math.sin(an)*r))),q=add(a,add(mul(right,Math.cos(next)*r),mul(front,Math.sin(next)*r)));this.triangle(p,q,b,unit(add(mul(right,Math.cos((an+next)/2)),mul(front,Math.sin((an+next)/2)))),col);}}
 cone(x,y,z,r,h,col){for(let i=0;i<8;i++){const a=i/8*Math.PI*2,b=(i+1)/8*Math.PI*2;const p=V(x+Math.cos(a)*r,y,z+Math.sin(a)*r),q=V(x+Math.cos(b)*r,y,z+Math.sin(b)*r),top=V(x,y+h,z);this.triangle(p,q,top,unit(V(Math.cos((a+b)/2),r/h,Math.sin((a+b)/2))),col);}}
}
export class Renderer {
 constructor(canvas){this.canvas=canvas;const gl=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'high-performance'})||canvas.getContext('experimental-webgl');if(!gl)return new CanvasRenderer(canvas);this.gl=gl;
 const vertex='attribute vec3 aPosition; attribute vec3 aNormal; attribute vec3 aColor; uniform mat4 uVP; uniform vec3 uEye; uniform float uAmbient; varying vec3 vColor; varying float vDist; void main(){ float light=uAmbient+(1.0-uAmbient)*max(dot(normalize(aNormal),normalize(vec3(-0.4,0.9,0.3))),0.0); float emissive=step(1.01,max(aColor.r,max(aColor.g,aColor.b))); vColor=mix(aColor*light,aColor,emissive); vDist=distance(aPosition,uEye); gl_Position=uVP*vec4(aPosition,1.0); }';
 const fragment='precision mediump float; varying vec3 vColor; varying float vDist; uniform vec3 uSky; uniform vec2 uFog; void main(){ float fog=smoothstep(uFog.x,uFog.y,vDist); vec3 sky=uSky; vec3 neon=vColor/(vec3(1.0)+max(vColor-1.0,0.0)*0.35); gl_FragColor=vec4(mix(neon,sky,fog),1.0); }';
 const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;};const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));gl.useProgram(p);this.program=p;this.vp=gl.getUniformLocation(p,'uVP');this.eye=gl.getUniformLocation(p,'uEye');this.skyUniform=gl.getUniformLocation(p,'uSky');this.fogUniform=gl.getUniformLocation(p,'uFog');this.ambientUniform=gl.getUniformLocation(p,'uAmbient');this.position=gl.getAttribLocation(p,'aPosition');this.normal=gl.getAttribLocation(p,'aNormal');this.col=gl.getAttribLocation(p,'aColor');for(const a of [this.position,this.normal,this.col])gl.enableVertexAttribArray(a);gl.enable(gl.DEPTH_TEST);gl.clearColor(.025,.055,.12,1);this.dynamic=gl.createBuffer();this.lineBuffer=gl.createBuffer();this.resize();}
 resize(){const dpr=Math.min(devicePixelRatio||1,1.6);this.width=innerWidth;this.height=innerHeight;this.canvas.width=Math.round(this.width*dpr);this.canvas.height=Math.round(this.height*dpr);this.gl.viewport(0,0,this.canvas.width,this.canvas.height);}
 upload(geometry){const gl=this.gl,bins=new Map(),d=geometry.data;for(let i=0;i<d.length;i+=27){const x=(d[i]+d[i+9]+d[i+18])/3,z=(d[i+2]+d[i+11]+d[i+20])/3;const span=Math.max(Math.abs(d[i]-d[i+9]),Math.abs(d[i]-d[i+18]),Math.abs(d[i+2]-d[i+11]),Math.abs(d[i+2]-d[i+20]));const key=span>200?'ground':Math.floor(x/110)+','+Math.floor(z/110);if(!bins.has(key))bins.set(key,{data:[],x0:Infinity,x1:-Infinity,z0:Infinity,z1:-Infinity});const bin=bins.get(key);for(let j=i;j<i+27;j++){bin.data.push(d[j]);if((j-i)%9===0){bin.x0=Math.min(bin.x0,d[j]);bin.x1=Math.max(bin.x1,d[j]);bin.z0=Math.min(bin.z0,d[j+2]);bin.z1=Math.max(bin.z1,d[j+2]);}}}const chunks=[];for(const [key,bin] of bins){const buffer=gl.createBuffer(),array=new Float32Array(bin.data);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,array,gl.STATIC_DRAW);chunks.push({buffer,count:array.length/9,x:(bin.x0+bin.x1)/2,z:(bin.z0+bin.z1)/2,r:Math.hypot(bin.x1-bin.x0,bin.z1-bin.z0)/2,always:key==='ground'});}return{chunks,count:d.length/9};}
 bind(buffer){const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.vertexAttribPointer(this.position,3,gl.FLOAT,false,36,0);gl.vertexAttribPointer(this.normal,3,gl.FLOAT,false,36,12);gl.vertexAttribPointer(this.col,3,gl.FLOAT,false,36,24);}
 render(staticMesh,dynamicGeometry,lines,eye,target){const gl=this.gl,env=this.environment||{sky:[.025,.055,.12],ambient:.48,fogNear:170,fogFar:640};gl.clearColor(...env.sky,1);gl.uniform3fv(this.skyUniform,env.sky);gl.uniform2f(this.fogUniform,env.fogNear,env.fogFar);gl.uniform1f(this.ambientUniform,env.ambient);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.matrix=multiply(perspective(Math.PI/3,this.width/this.height,.15,1500),lookAt(eye,target));gl.uniformMatrix4fv(this.vp,false,this.matrix);gl.uniform3f(this.eye,eye.x,eye.y,eye.z);for(const chunk of staticMesh.chunks){if(!chunk.always&&Math.hypot(chunk.x-eye.x,chunk.z-eye.z)>520+chunk.r)continue;this.bind(chunk.buffer);gl.drawArrays(gl.TRIANGLES,0,chunk.count);}this.bind(this.dynamic);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(dynamicGeometry.data),gl.DYNAMIC_DRAW);gl.drawArrays(gl.TRIANGLES,0,dynamicGeometry.data.length/9);
 if(lines.length){const data=[];for(const l of lines)for(const p of [l.a,l.b])data.push(p.x,p.y,p.z,0,1,0,...l.color);this.bind(this.lineBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.DYNAMIC_DRAW);gl.drawArrays(gl.LINES,0,data.length/9);}}
 project(p){const m=this.matrix;if(!m)return null;const w=m[3]*p.x+m[7]*p.y+m[11]*p.z+m[15];if(w<=0)return null;const x=(m[0]*p.x+m[4]*p.y+m[8]*p.z+m[12])/w,y=(m[1]*p.x+m[5]*p.y+m[9]*p.z+m[13])/w;return{x:(x+1)/2*this.width,y:(1-y)/2*this.height,visible:Math.abs(x)<.9&&Math.abs(y)<.9};}
}

// Perspective 3D fallback for browsers where WebGL is unavailable.
export class CanvasRenderer {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});if(!this.ctx)throw new Error('浏览器无法绘制游戏，请用 Safari 或 Chrome 打开。');this.lastDraw=0;this.resize();}
 resize(){const dpr=Math.min(devicePixelRatio||1,1.25);this.width=innerWidth;this.height=innerHeight;this.canvas.width=Math.round(this.width*dpr);this.canvas.height=Math.round(this.height*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);}
 faces(data){const list=[];for(let i=0;i<data.length;){const same=i+54<=data.length&&[3,4,5,6,7,8].every(k=>data[i+k]===data[i+27+k]);const indices=same?[0,9,18,45]:[0,9,18],points=indices.map(k=>V(data[i+k],data[i+k+1],data[i+k+2])),normal=V(data[i+3],data[i+4],data[i+5]),light=.48+.52*Math.max(dot(unit(normal),unit(V(-.4,.9,.3))),0);const emissive=Math.max(data[i+6],data[i+7],data[i+8])>1.01,rgb=[data[i+6],data[i+7],data[i+8]].map(v=>emissive?v/(1+Math.max(v-1,0)*.35):v*light);
 const emit=pts=>{const center=mul(pts.reduce((a,b)=>add(a,b),V()),1/pts.length);list.push({points:pts,center,normal,rgb,radius:Math.max(...pts.map(p=>length(sub(p,center)))),css:[]});};
 // Split large surfaces so roof / facade centers cannot paint over nearby actors and windows.
 if(same){const w=length(sub(points[1],points[0])),h=length(sub(points[3],points[0])),tile=Math.max(w,h)>300?70:12,cols=Math.min(32,Math.max(1,Math.ceil(w/tile))),rows=Math.min(32,Math.max(1,Math.ceil(h/tile)));const at=(u,v)=>mix(mix(points[0],points[1],u),mix(points[3],points[2],u),v);for(let y=0;y<rows;y++)for(let x=0;x<cols;x++)emit([at(x/cols,y/rows),at((x+1)/cols,y/rows),at((x+1)/cols,(y+1)/rows),at(x/cols,(y+1)/rows)]);}else emit(points);i+=same?54:27;}return list;}

 upload(geometry){const faces=this.faces(geometry.data),bins=new Map(),large=[];for(const f of faces){if(f.radius>85){large.push(f);continue;}const key=Math.floor(f.center.x/110)+','+Math.floor(f.center.z/110);if(!bins.has(key))bins.set(key,[]);bins.get(key).push(f);}const groups=[...bins.values()].map(items=>{const xs=items.map(f=>f.center.x),ys=items.map(f=>f.center.y),zs=items.map(f=>f.center.z);const center=V((Math.min(...xs)+Math.max(...xs))/2,(Math.min(...ys)+Math.max(...ys))/2,(Math.min(...zs)+Math.max(...zs))/2);return{faces:items,center,radius:Math.max(...items.map(f=>length(sub(f.center,center))+f.radius))};});return{faces,groups,large};}
 render(staticMesh,dynamicGeometry,lines,eye,target){this.matrix=multiply(perspective(Math.PI/3,this.width/this.height,.15,1500),lookAt(eye,target));const now=performance.now();if(now-this.lastDraw<32)return;this.lastDraw=now;
 const env=this.environment||{sky:[.025,.055,.12],ambient:.48,fogNear:170,fogFar:640,phase:'night'},ctx=this.ctx,W=this.width,H=this.height,forward=unit(sub(target,eye)),right=unit(cross(forward,V(0,1,0))),up=cross(right,forward),scale=H*.8660254,tanY=.57735,tanX=tanY*W/H;
 const view=p=>{const d=sub(p,eye);return{x:dot(d,right),y:dot(d,up),z:dot(d,forward)};};
 const project=p=>({x:W/2+p.x/p.z*scale,y:H/2-p.y/p.z*scale});
 const clipNear=points=>{const out=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],ina=a.z>=.2,inb=b.z>=.2;if(ina)out.push(a);if(ina!==inb){const t=(.2-a.z)/(b.z-a.z);out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:.2});}}return out;};
 const visible=[...(staticMesh.large||[])];for(const group of staticMesh.groups||[]){const c=view(group.center),r=group.radius;if(c.z+r<.2||c.z-r>370||Math.abs(c.x)>Math.max(0,c.z)*tanX+r*1.8||Math.abs(c.y)>Math.max(0,c.z)*tanY+r*1.8)continue;visible.push(...group.faces);}if(!staticMesh.groups)visible.push(...staticMesh.faces);visible.push(...this.faces(dynamicGeometry.data));const queue=[];for(const f of visible){const diff=sub(f.center,eye);if(dot(f.normal,mul(diff,-1))<-.05)continue;const c=view(f.center),r=f.radius;if(c.z+r<.2||c.z-r>370||Math.abs(c.x)>Math.max(0,c.z)*tanX+r*1.8||Math.abs(c.y)>Math.max(0,c.z)*tanY+r*1.8)continue;
 if(c.z>80&&r*scale/c.z<.9)continue;const clipped=clipNear(f.points.map(view));if(clipped.length<3)continue;const points=clipped.map(project);if(points.every(p=>p.x<0)||points.every(p=>p.x>W)||points.every(p=>p.y<0)||points.every(p=>p.y>H))continue;
 const bin=clamp(Math.floor((c.z-env.fogNear)/(env.fogFar-env.fogNear)*12),0,12),key=bin+'|'+env.phase;if(!f.css[key]){const fog=bin/12;f.css[key]='rgb('+f.rgb.map((v,i)=>Math.round((v*(1-fog)+env.sky[i]*fog)*255)).join(',')+')';}queue.push({points,depth:c.z,fill:f.css[key],floor:f.normal.y>.99&&f.center.y<=.5,height:f.center.y});}
 queue.sort((a,b)=>a.floor!==b.floor?(a.floor?-1:1):a.floor&&Math.abs(a.height-b.height)>.005?a.height-b.height:b.depth-a.depth);ctx.fillStyle='rgb('+env.sky.map(v=>Math.round(v*255)).join(',')+')';ctx.fillRect(0,0,W,H);for(const f of queue){ctx.beginPath();ctx.moveTo(f.points[0].x,f.points[0].y);for(let i=1;i<f.points.length;i++)ctx.lineTo(f.points[i].x,f.points[i].y);ctx.closePath();ctx.fillStyle=f.fill;ctx.fill();}
 for(const l of lines){const a=view(l.a),b=view(l.b);if(a.z<.2||b.z<.2)continue;const pa=project(a),pb=project(b);ctx.strokeStyle='rgb('+l.color.map(c=>Math.round(c*255)).join(',')+')';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();}}
 project(p){return Renderer.prototype.project.call(this,p);}
}
