import{V,sub,length,color}from'./engine3d.js?v=20261006achv';
import{installSettings,DEFAULT_KEYS}from'./settings.js?v=20261006achv';
import{AchievementSystem,ACHIEVEMENTS}from'./achievements.js?v=20261006achv';
import{normalizeKeys}from'./settings-model.js?v=20261006achv';
export{DEFAULT_KEYS};
export function installFeatures(sim,canvas,callbacks){const $=id=>document.getElementById(id);const keys={...DEFAULT_KEYS};let active=null,saveTime=0,captureRequested=false;let filter='none',zoom=17;
 let saved=null;try{saved=JSON.parse(localStorage.getItem('spider-neon-adventure')||'null');if(saved){if(['peter','gwen','miles'].includes(saved.character))sim.character=saved.character;if(['easy','normal','hard'].includes(saved.difficulty))sim.difficulty=saved.difficulty;sim.style=Math.max(0,Math.min(100000,Number(saved.style)||0));sim.raceBest=Number.isFinite(saved.raceBest)?saved.raceBest:null;if(Array.isArray(saved.visited))sim.visited=new Set(saved.visited.filter(n=>typeof n==='string'));if(Array.isArray(saved.backpacks))sim.backpacks.forEach((b,i)=>b.found=!!saved.backpacks[i]);if(saved.raceGhost&&saved.raceGhost.time>0&&Array.isArray(saved.raceGhost.samples))sim.raceGhost={time:Number(saved.raceGhost.time)||0,samples:saved.raceGhost.samples.filter(a=>Array.isArray(a)&&a.length===3).slice(0,3000)};if(saved.keys)Object.assign(keys,normalizeKeys(saved.keys));}}
 catch{}const achievements=sim.achievements=new AchievementSystem(sim);achievements.load(saved);if(saved&&saved.stats&&sim.stats)for(const k in sim.stats)if(typeof sim.stats[k]==='number')sim.stats[k]=Number(saved.stats[k])||0;
function persist(){try{localStorage.setItem('spider-neon-adventure',JSON.stringify({character:sim.character,difficulty:sim.difficulty,style:sim.style,raceBest:sim.raceBest,visited:[...sim.visited],backpacks:sim.backpacks.map(b=>b.found),keys,achievements:[...achievements.unlocked],stats:{...sim.stats},raceGhost:sim.raceGhost||null}));}catch{}}
 function close(){if(!active)return false;$(active+'Overlay').hidden=true;if(active==='settings'){settingsUI.save();settingsUI.disposeCapture();}if(active==='photo'){document.body.classList.remove('photo-mode');canvas.style.filter='';callbacks.photo(false);}active=null;callbacks.resume();return true;}
 function open(name){if(name==='photo'&&!sim.options.photo){callbacks.toast('拍照模式已关闭，可以在设置中开启。');return;}if(active)close();active=name;$(name+'Overlay').hidden=false;callbacks.freeze(name==='photo');if(name==='photo'){document.body.classList.add('photo-mode');callbacks.photo(true);canvas.style.filter=filter;}if(name==='journal')journal();if(name==='settings')settingsUI.open();}
 function characters(){document.querySelectorAll('[data-character]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.character===sim.character));b.classList.toggle('selected',b.dataset.character===sim.character);});$('characterName').textContent={peter:'彼得 · 平衡型',gwen:'格温 · 特技风格加成',miles:'迈尔斯 · 电能蛛网'}[sim.character];}
 document.querySelectorAll('[data-character]').forEach(b=>b.onclick=()=>{sim.character=b.dataset.character;characters();persist();});characters();
 $('journalButton').onclick=()=>open('journal');$('settingsButton').onclick=()=>open('settings');$('photoButton').onclick=()=>open('photo');$('closeJournal').onclick=close;$('closeSettings').onclick=close;$('closePhoto').onclick=close;
 $('skillsButton').onclick=()=>{$('skillsTray').hidden=!$('skillsTray').hidden;};document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{callbacks.skill(b.dataset.skill);$('skillsTray').hidden=true;});
 function journal(){const bossCount=sim.world.bosses.filter(b=>b.dead).length,events=sim.events.filter(e=>e.state==='done').length;$('storyText').textContent=bossCount===3?'城市的能源危机暂时解决了。自由探索、帮助居民，故事还在继续。':events?'居民带来线索：能源装置失窃，与三个反派有关。调查城区并选择你想挑战的 Boss。':'能源装置失窃后，城市接连发生异常。先帮助屋顶的居民，或自由前往任意城区寻找线索。';const st=sim.stats||{},dur=Math.floor((st.playTime||0)/60),sec=Math.floor((st.playTime||0)%60);const journalStats=$('journalStats');journalStats.replaceChildren();for(const [k,v] of [['游玩时长',dur+' 分 '+sec+' 秒'],['风格',sim.style],['摆荡距离',Math.round(st.flightDistance||0)],['最高速度',Math.round(st.maxSpeed||0)],['蛛丝发射',st.websFired||0],['击败敌人',st.enemiesDefeated||0],['市民交谈',st.citizenTalks||0],['完美闪避',st.perfectDodges||0],['空中特技',st.tricks||0],['救援',events+' / '+sim.events.length],['背包',sim.backpacks.filter(b=>b.found).length+' / 5'],['地标照片',sim.photos.size+' / 4'],['成就',achievements.unlocked.size+' / '+ACHIEVEMENTS.length]]){const tile=document.createElement('div');tile.innerHTML='<b>'+v+'</b><small>'+k+'</small>';journalStats.appendChild(tile);}
const achievementList=$('achievementList');achievementList.replaceChildren();for(const a of ACHIEVEMENTS){const done=achievements.unlocked.has(a.id),row=document.createElement('div');row.className='achievement'+(done?' done':'');row.innerHTML='<b>'+(done?'✓ ':'')+a.name+'</b><small>'+(done?'风格 +'+a.reward:a.desc)+'</small>';achievementList.appendChild(row);}const ultimate=document.createElement('div');ultimate.className='ultimate'+(achievements.complete?' done':'');ultimate.textContent=achievements.complete?'👑 城市传奇 · 午夜鎏金战衣已在织光服装店备好':'？？？ 织光服装店的镇店战衣，等待达成全部成就的城市传奇。';achievementList.appendChild(ultimate);$('eventList').replaceChildren();sim.events.forEach((event,i)=>{if(!sim.options.events)return;const b=document.createElement('button');b.innerHTML='<b>'+event.name+(event.state==='done'?' ✓':'')+'</b><small>'+event.story+'</small>';b.onclick=()=>{if(sim.interior)sim.exitShop();sim.ropes=[null,null];sim.p=V(event.p.x,event.p.y,event.p.z+8);sim.v=V();callbacks.resetCamera();close();callbacks.toast('已到'+event.name+'附近，靠近居民按互动。');};$('eventList').appendChild(b);});$('backpackNotes').textContent=sim.backpacks.filter(b=>b.found).map(b=>b.text).join('\n')||'找到屋顶上亮着蓝灯的背包，可以读到城市的小故事。';$('raceBest').textContent=sim.raceBest===null?'个人最佳：尚无记录':'个人最佳：'+sim.raceBest.toFixed(1)+' 秒';}
 $('startRace').onclick=()=>{sim.startRace();callbacks.resetCamera();close();};$('restButton').onclick=()=>{if(sim.restOnRoof()){close();callbacks.toast('蹲在屋顶看风景，移动或点起身继续探索。');}};$('hangButton').onclick=()=>{if(sim.hangFromRoof()){callbacks.resetCamera();close();callbacks.toast('蛛丝倒挂中，可以转动镜头看风景。');}};$('stopRest').onclick=()=>sim.stopRest();$('startStunts').onclick=()=>{if(sim.startStunts())close();};
 const settingsUI=installSettings(sim,keys,{...callbacks,labels:()=>{document.querySelectorAll('[data-action],[data-skill]').forEach(b=>{const a=b.dataset.action||b.dataset.skill;if(keys[a])b.querySelector('small').textContent=keys[a]===' '?'SPACE':keys[a].toUpperCase();});}});
 achievements.onunlock=fresh=>{callbacks.toast('🏆 成就达成：'+fresh.map(a=>a.name).join('、')+' · 风格 +'+fresh.reduce((n,a)=>n+a.reward,0));settingsUI.audio.achievement();persist();};
 $('photoFilter').onchange=()=>{filter={none:'none',cinema:'contrast(1.15) saturate(.75)',mono:'grayscale(1) contrast(1.2)',neon:'saturate(1.55) contrast(1.1)'}[$('photoFilter').value];canvas.style.filter=filter;};$('photoZoom').oninput=()=>zoom=Number($('photoZoom').value);$('photoSave').onclick=()=>{captureRequested=true;};
 const weather=$('weather'),ctx=weather.getContext('2d');function effects(t){const w=innerWidth,h=innerHeight;if(weather.width!==w||weather.height!==h){weather.width=w;weather.height=h;}ctx.clearRect(0,0,w,h);if(sim.interior)return;const speed=Math.hypot(sim.v.x,sim.v.z);if(sim.weather==='rain'){ctx.strokeStyle='#a7daee70';ctx.lineWidth=1;for(let i=0;i<100;i++){const x=(i*131.77+t*.09)%w,y=(i*73.17+t*.37)%h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-7,y+19);ctx.stroke();}}if(sim.weather==='fog'){const fog=ctx.createLinearGradient(0,0,0,h);fog.addColorStop(0,'#8098b155');fog.addColorStop(.6,'#b6d8ed22');fog.addColorStop(1,'#b6d8ed00');ctx.fillStyle=fog;ctx.fillRect(0,0,w,h);}if(speed>45){ctx.strokeStyle='rgba(186,237,255,'+Math.min(.35,(speed-45)/200)+')';for(let i=0;i<28;i++){const a=i*2.3999,r=.7+(t*.001+i*.17)%1.2,x=w/2+Math.cos(a)*w*r,y=h*.47+Math.sin(a)*h*r;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(a)*30,y+Math.sin(a)*30);ctx.stroke();}}}
 return{audio:settingsUI.audio,get active(){return active;},get zoom(){return zoom;},get filter(){return filter;},close,keyLabel(action){return(keys[action]||'').toUpperCase();},key(raw){const k=raw.toLowerCase();for(const action in keys)if(keys[action]===k)return DEFAULT_KEYS[action];return k==='escape'?k:'__unbound__';},tick(dt,t){achievements.tick(dt);saveTime+=dt;if(saveTime>5){persist();saveTime=0;}$('styleScore').textContent=sim.style;$('comboCount').textContent=sim.stuntChallenge?'特技挑战 '+Math.ceil(sim.stuntChallenge.left)+' 秒 · '+sim.stuntChallenge.score+' 分':sim.comboTime>0?'×'+sim.combo:'自由探索';$('sense').textContent=sim.sense;$('sense').hidden=!sim.sense;const bound=sim.targets().filter(b=>b.bound>0);$('bindStatus').hidden=!bound.length;if(bound.length)$('bindStatus').textContent='蛛丝捆缚 '+bound.length+' 位 · '+Math.max(...bound.map(b=>b.bound)).toFixed(1)+' 秒';$('stopRest').hidden=!sim.resting&&!sim.hanging;settingsUI.syncVisibility();document.body.classList.toggle('slow-motion',sim.slowTime>0);effects(t);if(captureRequested){captureRequested=false;const shot=document.createElement('canvas');shot.width=canvas.width;shot.height=canvas.height;const c=shot.getContext('2d');c.filter=filter;c.drawImage(canvas,0,0);c.filter='none';c.drawImage(weather,0,0,shot.width,shot.height);shot.toBlob(blob=>{if(!blob){callbacks.toast('这次照片没有保存成功，请再试一次。');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='spider-city-'+Date.now()+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');sim.world.districts.forEach((d,i)=>{if(length(sub(sim.p,V(d.b.x,d.b.h,d.b.z)))<160)sim.photos.add(i);});callbacks.toast('城市照片已保存，地标打卡 '+sim.photos.size+' / 4。');}}};
}
