import {V,add,sub,mul,length,unit,clamp,mix,color,Geometry,Renderer} from './engine3d.js?v=20261006achv';
import {createWorld,Simulation,makeHero,makeBoss,makeCityLife,PALETTE,firstWall} from './world3d.js?v=20261006achv';
import{Adventure,makePlayer,makeAdventure}from'./adventure.js?v=20261006achv';
import{installFeatures}from'./features.js?v=20261006achv';
import{ULTIMATE_SUIT}from'./achievements.js?v=20261006achv';
const $=id=>document.getElementById(id),canvas=$('game'),world=createWorld(),sim=new Adventure(world);
let renderer;
try{renderer=new Renderer(canvas);}catch(e){$('error').hidden=false;$('error').textContent=e.message;$('start').disabled=true;$('start').textContent='3D 画面无法启动';throw e;}
const city=renderer.upload(world.geometry);world.geometry.data=[];let activeMesh=city,sceneKey=null;const shopMeshes=new Map();
const keyboard={},held=new Map(),pulse={};let stick={x:0,y:0},stickPointer=null,lookPointer=null,lookLast=null;
let photoMode=false,features;let started=false,running=false,paused=false,yaw=0,pitch=.21,last=0,toastTimer=0,hudTimer=0,radarTimer=0;
let camera=add(sim.p,V(0,10,22)),cameraTarget=add(sim.p,V(0,1.5,0));let hookTipShown=false;
const input=()=>({forward:clamp((keyboard.w?1:0)-(keyboard.s?1:0)-stick.y,-1,1),right:clamp((keyboard.d?1:0)-(keyboard.a?1:0)+stick.x,-1,1),jump:!!keyboard.jump||hasHeld('jump'),webLeft:!!keyboard.q||hasHeld('webLeft'),webRight:!!keyboard.e||hasHeld('webRight'),attack:!!keyboard.f||hasHeld('attack'),climb:!!keyboard.c||hasHeld('climb')});
const hasHeld=k=>[...held.values()].includes(k)||(pulse[k]||0)>performance.now();
function triggerAction(action){if(!running||!action)return;features?.audio.effect(action);if(sim.hanging||sim.resting)sim.stopRest();if(['boost','zip','pull','trick','dodge','net','light','heavy','bind'].includes(action)){sim.skill(action,yaw);return;}const now=performance.now();pulse[action]=now+(action==='webLeft'||action==='webRight'?140:100);if(action==='webLeft'||action==='webRight'){const side=action==='webLeft'?0:1;if(!sim.ropes[side])sim.attach(side,yaw);sim.previousHook[side]=true;}else if(action==='attack')sim.attack();}
function toast(msg,seconds=4){$('toast').textContent=msg;$('toast').style.opacity=1;toastTimer=seconds;}
function clearInput(){for(const k of Object.keys(keyboard))keyboard[k]=false;held.clear();for(const k of Object.keys(pulse))delete pulse[k];stick={x:0,y:0};$('knob').style.transform='';stickPointer=null;lookPointer=null;sim.resetInput();for(const b of document.querySelectorAll('.held'))b.classList.remove('held');}
function start(){if(!started){started=true;toast('按住右手蛛丝试试！拖动画面可以转动镜头。',7);}running=true;paused=false;$('overlay').hidden=true;$('pause').textContent='Ⅱ';clearInput();}
$('start').onclick=start;
function pause(){if(!started)return;paused=!paused;running=!paused;clearInput();$('overlay').hidden=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('start').textContent='继续飞行';}
$('pause').onclick=pause;$('help').onclick=()=>{if(!started)return;paused=false;pause();};
function closeMap(){ $('mapOverlay').hidden=true;paused=false;running=started;clearInput();}
$('mapButton').onclick=()=>{if(!started)return;paused=true;running=false;clearInput();$('mapOverlay').hidden=false;drawMap($('cityMap'),true);renderPlaces();};$('closeMap').onclick=closeMap;
function renderPlaces(){const p=$('mapPlaces');p.replaceChildren();world.districts.forEach((d,i)=>{const b=sim.options.combat&&sim.options.bossChallenge?world.bosses[i-1]:null,button=document.createElement('button');button.innerHTML='<span>'+d.name+'</span><small>'+(b?(b.dead?'已击败 · 再次挑战':b.name+' · 前往挑战'):'安全起点 · 练习飞行')+'</small>';button.onclick=()=>{sim.teleport(i);syncScene();yaw=0;pitch=.21;camera=add(sim.p,V(0,10,22));cameraTarget=add(sim.p,V(0,1.5,0));closeMap();};p.appendChild(button);});world.shops.forEach((shop,i)=>{if(!((world.shops.find(q=>q.category===shop.category)===shop)||(shop.b.j===2&&shop.b.i>=-1&&shop.b.i<=1)||([3,4,5].includes(shop.type)&&world.shops.filter(q=>q.type===shop.type).sort((a,b)=>length(sub(a.door,world.spawn))-length(sub(b.door,world.spawn)))[0]===shop)))return;const button=document.createElement('button');button.innerHTML='<span>'+shop.name+'</span><small>街边小店 · 可以进入</small>';button.onclick=()=>{sim.visitShop(i);syncScene();yaw=0;pitch=.18;camera=add(sim.p,V(0,7,16));cameraTarget=add(sim.p,V(0,1.4,0));closeMap();};p.appendChild(button);});for(const place of [{name:'埃菲尔铁塔风情广场',p:V(55,1.6,110)},{name:'时代广场风情步行街',p:V(-55,1.6,110)},...world.places]){const button=document.createElement('button');button.innerHTML='<span>'+place.name+'</span><small>地标观景 · 自由漫步</small>';button.onclick=()=>{sim.stopRest();if(sim.interior)sim.exitShop();sim.p={...place.p};sim.v=V();sim.resetInput();syncScene();yaw=0;camera=add(sim.p,V(0,7,16));closeMap();};p.appendChild(button);}}
function syncScene(){const key=sim.interior?sim.interior.shop.type:null;if(key===sceneKey)return;sceneKey=key;if(key===null)activeMesh=city;else{if(!shopMeshes.has(key))shopMeshes.set(key,renderer.upload(sim.interior.geometry));activeMesh=shopMeshes.get(key);sim.interior.geometry.data=[];}yaw=0;pitch=.18;camera=add(sim.p,V(0,6,12));cameraTarget=add(sim.p,V(0,1.4,0));clearInput();$('exitShop').hidden=key===null;}
function interact(){if(!running)return;features?.audio.effect('interact');if(sim.interior){if(length(sub(sim.p,V(0,1.6,24)))<4.5){sim.exitShop();syncScene();return;}openShopMenu();return;}const shop=sim.nearbyShop();if(shop){sim.enterShop(shop);syncScene();}else if(sim.interactActivity())return;else toast('沿街寻找亮着招牌的小店，靠近店门就可以进入。');}
$('interact').onclick=interact;$('exitShop').onclick=()=>{sim.exitShop();syncScene();};
function closeShopMenu(){ $('shopOverlay').hidden=true;paused=false;running=started;clearInput();}
$('closeShop').onclick=closeShopMenu;
function openShopMenu(){const shop=sim.interior.shop;paused=true;running=false;clearInput();$('shopTitle').textContent=shop.name;$('shopWelcome').textContent=['店员：补给和纪念品都在这里，慢慢挑。','店员：欢迎试穿！选一套喜欢的战衣继续探索。','店员：打累了就坐下来，汉堡和薯条刚刚做好。','店员：欢迎！冰淇淋和柠檬茶刚做好。','店员：欢迎来花园餐厅，找个位置坐坐吧。','前台：欢迎入住，可以参观大厅和客房。'][shop.type];let names=shop.menu||[['能量饮料','星星饼干','城市明信片'],['经典红蓝战衣','极光科技战衣','霓虹夜行战衣','力量装甲战衣','星耀光轨战衣'],['招牌汉堡','香脆薯条','坐下休息'],['冰淇淋','柠檬茶','坐下休息'],['招牌套餐','甜点','坐下休息'],['前台交谈','入住客房','住宿到清晨']][shop.type],notes=[['恢复 25 点生命','恢复 35 点生命','收藏城市纪念品'],['平衡型 · 即刻试穿','冲刺恢复更快','降低敌人警觉','风格 120 解锁 · 重物拉拽','风格 300 解锁 · 特技光轨'],...Array.from({length:3},()=>['恢复 25 点生命','恢复 35 点生命','恢复全部生命']),['与前台互动','自由逛客房 · 恢复生命','恢复生命 · 时间切到清晨']][shop.type];$('shopWelcome').textContent=shop.type===1?$('shopWelcome').textContent:shop.type===5?$('shopWelcome').textContent:('欢迎来到'+shop.name+' · '+(shop.street||shop.category)+'，慢慢逛逛吧。');const ultimate=sim.achievements&&sim.achievements.complete;if(shop.type===1&&ultimate){names=[...names,ULTIMATE_SUIT.name+'战衣'];notes.push('全成就限定 · 城市传奇专属');}$('shopItems').replaceChildren();names.forEach((name,i)=>{const button=document.createElement('button');button.innerHTML='<span>'+name+'</span><small>'+notes[i]+'</small>';if(shop.type===1&&!sim.options.unlockSuits&&i>=3&&i<5&&sim.style<(i===3?120:300))button.disabled=true;button.onclick=()=>{sim.shopAction(i);closeShopMenu();};$('shopItems').appendChild(button);});$('shopOverlay').hidden=false;}
for(const shop of world.shops){const label=document.createElement('div');label.className='shop-label';label.innerHTML='<b>'+shop.name+'</b><small>可进入 · 逛店 R</small>';shop.label=label;$('shopLabels').appendChild(label);}
function drawShopLabels(){for(const shop of world.shops){const target=sim.interior?.shop===shop?V(0,7.7,-23.1):V(shop.b.x,shop.b.h+4,shop.door.z+1),screen=renderer.project(target),show=started&&(!sim.interior||sim.interior.shop===shop)&&length(sub(target,sim.p))<120&&screen?.visible&&(!sim.interior?!firstWall(camera,target,sim.occluders()):true);shop.label.hidden=!show;if(show){shop.label.style.left=screen.x+'px';shop.label.style.top=screen.y+'px';}}}
addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target?.tagName||''))return;const k=features?features.key(e.key):e.key.toLowerCase();if(['w','a','s','d','q','e','f','c','r',' ','arrowleft','arrowright','arrowup','arrowdown'].includes(k)){e.preventDefault();keyboard[k===' '?'jump':k]=true;if(!e.repeat&&k==='r')interact();if(!e.repeat)triggerAction(({c:'climb',q:'webLeft',e:'webRight',f:'attack',' ':'jump'})[k]);}if(!e.repeat){const skill={shift:'boost',z:'zip',g:'pull',t:'trick',v:'dodge',x:'net',j:'light',k:'heavy',b:'bind'}[k];if(skill){e.preventDefault();triggerAction(skill);}if(k==='p'&&started)$('photoButton').onclick();}if(e.key==='Escape'){if(features?.close())return;if(!$('shopOverlay').hidden)closeShopMenu();else if(!$('mapOverlay').hidden)closeMap();else pause();}});
addEventListener('keyup',e=>{const k=features?features.key(e.key):e.key.toLowerCase();keyboard[k===' '?'jump':k]=false;});
addEventListener('blur',()=>{clearInput();if(started&&running)pause();});
for(const btn of document.querySelectorAll('[data-action]')){btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);held.set(e.pointerId,btn.dataset.action);triggerAction(btn.dataset.action);btn.classList.add('held');});const up=e=>{held.delete(e.pointerId);if(!hasHeld(btn.dataset.action))btn.classList.remove('held');};btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);btn.addEventListener('lostpointercapture',up);}
const stickEl=$('stick');function moveStick(e){const r=stickEl.getBoundingClientRect(),radius=r.width*.35,dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,dist=Math.hypot(dx,dy),scale=dist>radius?radius/dist:1;stick={x:dx*scale/radius,y:dy*scale/radius};$('knob').style.transform='translate('+dx*scale+'px,'+dy*scale+'px)';}
stickEl.addEventListener('pointerdown',e=>{if(stickPointer!==null)return;e.preventDefault();stickPointer=e.pointerId;stickEl.setPointerCapture(e.pointerId);moveStick(e);});stickEl.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)moveStick(e);});function releaseStick(e){if(e.pointerId!==stickPointer)return;stickPointer=null;stick={x:0,y:0};$('knob').style.transform='';}stickEl.addEventListener('pointerup',releaseStick);stickEl.addEventListener('pointercancel',releaseStick);stickEl.addEventListener('lostpointercapture',releaseStick);
canvas.addEventListener('pointerdown',e=>{if((!running&&!photoMode)||lookPointer!==null)return;lookPointer=e.pointerId;lookLast={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer||(!running&&!photoMode))return;const sensitivity=.2+sim.options.sensitivity*.16;yaw-=(e.clientX-lookLast.x)*.005*sensitivity;pitch=clamp(pitch+(e.clientY-lookLast.y)*.004*sensitivity*(sim.options.invertY?-1:1),-.65,.9);lookLast={x:e.clientX,y:e.clientY};$('lookHint').style.opacity='.2';});function releaseLook(e){if(e.pointerId===lookPointer)lookPointer=null;}canvas.addEventListener('pointerup',releaseLook);canvas.addEventListener('pointercancel',releaseLook);canvas.addEventListener('lostpointercapture',releaseLook);canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();running=false;clearInput();$('error').hidden=false;$('error').textContent='3D 画面已中断，请刷新页面后继续。';$('overlay').hidden=false;$('start').disabled=true;});canvas.addEventListener('webglcontextrestored',()=>location.reload());
addEventListener('resize',()=>renderer.resize());
function rayBuilding(origin,end,b){const dir=sub(end,origin);let min=0,max=1;for(const [axis,lo,hi] of [['x',b.x-b.w/2-.8,b.x+b.w/2+.8],['y',0,b.h+1.5],['z',b.z-b.d/2-.8,b.z+b.d/2+.8]]){if(Math.abs(dir[axis])<.0001){if(origin[axis]<lo||origin[axis]>hi)return null;}else{let t1=(lo-origin[axis])/dir[axis],t2=(hi-origin[axis])/dir[axis];if(t1>t2)[t1,t2]=[t2,t1];min=Math.max(min,t1);max=Math.min(max,t2);if(min>max)return null;}}return min;}
function updateCamera(dt){const forward=V(-Math.sin(yaw),0,-Math.cos(yaw)),speed=Math.hypot(sim.v.x,sim.v.z),distance=photoMode?features.zoom:sim.interior?10:16.5+Math.min(speed*.1,9);const target=add(sim.p,V(0,1.4,0));const desired=add(sim.p,add(mul(forward,-distance*Math.cos(pitch)),V(0,3.5+distance*Math.sin(pitch),0)));if(sim.interior)desired.y=Math.min(10.8,desired.y);cameraTarget=mix(cameraTarget,target,1-Math.exp(-10*dt));camera=mix(camera,desired,1-Math.exp(-11*dt));const cameraHit=firstWall(cameraTarget,camera,sim.occluders(),.25),closest=cameraHit?.t??1;if(closest<1)camera=add(cameraTarget,mul(sub(camera,cameraTarget),Math.max(.08,closest-.03)));}
function drawMap(c,full=false){const ctx=c.getContext('2d'),w=c.width,h=c.height,s=Math.min(w,h)/(world.range*2+60),centerX=w/2,centerY=h/2;const xy=p=>({x:centerX+p.x*s,y:centerY+p.z*s});ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1b2f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1c3b4d';ctx.lineWidth=1;for(let i=-7;i<=7;i++){ctx.beginPath();ctx.moveTo(centerX+i*110*s,centerY-world.range*s);ctx.lineTo(centerX+i*110*s,centerY+world.range*s);ctx.stroke();ctx.beginPath();ctx.moveTo(centerX-world.range*s,centerY+i*110*s);ctx.lineTo(centerX+world.range*s,centerY+i*110*s);ctx.stroke();}ctx.fillStyle='#30594e';for(const park of world.parks){const p=xy(park);ctx.fillRect(p.x-35*s,p.y-35*s,70*s,70*s);}ctx.fillStyle='#29445a';for(const b of world.buildings){const p=xy(b);ctx.fillRect(p.x-b.w*s/2,p.y-b.d*s/2,b.w*s,b.d*s);}world.bosses.forEach((b,i)=>{if(!sim.options.combat||!sim.options.bossChallenge)return;const p=xy(b.p);ctx.fillStyle=b.dead?'#4c6d80':['#eabf9b','#65e2ff','#adeb8b'][i];ctx.beginPath();ctx.arc(p.x,p.y,full?5:3,0,Math.PI*2);ctx.fill();if(full){ctx.font='12px system-ui';ctx.fillText(b.name,p.x+9,p.y+4);}});for(const shop of world.shops){const p=xy(shop.door);ctx.fillStyle='#e6a1ff';ctx.fillRect(p.x-3,p.y-3,6,6);if(full&&length(sub(shop.door,sim.p))<180){ctx.font='11px system-ui';ctx.fillText(shop.name,p.x+7,p.y+13);}}const p=xy(sim.interior?sim.interior.shop.door:sim.p);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-yaw);ctx.fillStyle='#ff536b';ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(5,5);ctx.lineTo(0,2);ctx.lineTo(-5,5);ctx.closePath();ctx.fill();ctx.restore();if(full){ctx.font='11px system-ui';ctx.fillStyle='#adc2d5';ctx.fillText('红色箭头是你的位置',14,h-14);}}
function updateHUD(){for(let i=0;i<2;i++){const button=document.querySelector('[data-action="'+(i===0?'webLeft':'webRight')+'"]');button.classList.toggle('connected',!!sim.ropes[i]);button.querySelector('small').textContent=sim.ropes[i]?'已挂住 · 松手飞出':(features?.keyLabel(i===0?'webLeft':'webRight')||(i===0?'Q':'E'))+' · 按住';} $('health').style.width=sim.hp+'%';$('hp').textContent=Math.ceil(sim.hp);$('count').textContent='Boss '+world.bosses.filter(b=>b.dead).length+' / 3';$('speed').querySelector('b').textContent=Math.round(Math.hypot(sim.v.x,sim.v.z));$('interact').querySelector('span').textContent=sim.interior?'店内互动':sim.nearbyShop()?'进入小店':sim.nearbyActivity()?.line?'与市民交谈':sim.nearbyActivity()?.kind==='conflict'?'帮助邻居':sim.nearbyActivity()?'帮助 / 收集':'互动';$('interact').querySelector('small').textContent=(features?.keyLabel('interact')||'R')+' · 逛店 / 帮助';$('townCount').textContent='逛店 '+sim.visited.size+' / '+world.shops.length;$('climbStatus').hidden=!sim.climbing;if(sim.climbing)$('climbStatus').textContent=sim.ceilingCrawl?'倒挂爬行 · 摇杆移动':'攀墙中 · 摇杆向上 / 下，左右移动';const nearest=world.districts.reduce((a,b)=>length(sub(sim.p,V(a.b.x,a.b.h,a.b.z)))<length(sub(sim.p,V(b.b.x,b.b.h,b.b.z)))?a:b);$('location').textContent=sim.interior?sim.interior.shop.name:sim.nearbyShop()?.name||nearest.name;const boss=world.bosses.filter(b=>sim.options.combat&&sim.options.bossChallenge&&!sim.interior&&!b.dead&&length(sub(b.p,sim.p))<165).sort((a,b)=>length(sub(a.p,sim.p))-length(sub(b.p,sim.p)))[0];$('bossHUD').hidden=!boss;if(boss){$('bossName').textContent=boss.name;$('bossHealth').style.width=boss.hp/boss.max*100+'%';$('warning').textContent=boss.warning>0&&sim.options.sense?['准备冲锋 · 跳跃躲开','蓄力闪电 · 保持移动','准备投弹 · 离开落点'][boss.type]:'靠近后按蛛丝攻击';}}
function drawAnchors(){for(let i=0;i<2;i++){const el=$(i===0?'anchorLeft':'anchorRight');if(!started||!running){el.hidden=true;continue;}const candidate=sim.ropes[i]?{anchor:sim.ropes[i].anchor}:sim.selectHook(i,yaw);const screen=candidate?renderer.project(candidate.anchor):null;el.hidden=!(screen&&screen.visible);if(screen?.visible){el.style.left=screen.x+'px';el.style.top=screen.y+'px';el.style.borderColor=sim.ropes[i]?'#ffffff':'#8beaffaa';}}}
let clock=0,lastVisual=-Infinity;
function frame(t){const delta=Math.min((t-last)/1000,.05);last=t;clock+=delta;if(running){const sensitivity=.2+sim.options.sensitivity*.16,ySign=sim.options.invertY?-1:1;if(keyboard.arrowleft)yaw+=delta*1.5*sensitivity;if(keyboard.arrowright)yaw-=delta*1.5*sensitivity;if(keyboard.arrowup)pitch=clamp(pitch-delta*.8*sensitivity*ySign,-.65,.9);if(keyboard.arrowdown)pitch=clamp(pitch+delta*.8*sensitivity*ySign,-.65,.9);sim.aimPitch=pitch;let left=delta*(sim.slowTime>0?.32:1);const state=input();while(left>0){const dt=Math.min(left,1/120);sim.update(dt,state,yaw);left-=dt;}syncScene();updateCamera(delta);if(sim.ropes.some(Boolean)&&!hookTipShown){toast('挂住了！推动摇杆助推，松开蛛丝借惯性飞出去。',5);hookTipShown=true;}if(sim.messages.length){toast(sim.messages[sim.messages.length-1]);sim.messages=[];}if(toastTimer>0){toastTimer-=delta;if(toastTimer<=0)$('toast').style.opacity=0;}}
 features.tick(delta,t);features.audio.tick(delta,running);hudTimer+=delta;radarTimer+=delta;if(hudTimer>.1){updateHUD();hudTimer=0;}if(radarTimer>.2){drawMap($('radar'));radarTimer=0;}if(!renderer.gl&&t-lastVisual<40){requestAnimationFrame(frame);return;}lastVisual=t;const geometry=new Geometry(),lines=[];if(!sim.interior)makeCityLife(geometry,sim.time,sim.p);if(photoMode||sim.inv<=0||Math.floor(clock*12)%2===0)makePlayer(geometry,sim);makeAdventure(geometry,sim);for(const b of world.bosses)if(sim.options.combat&&sim.options.bossChallenge&&!sim.interior&&length(sub(b.p,sim.p))<400)makeBoss(geometry,b,sim.options);
 for(let i=0;i<2;i++){const r=sim.ropes[i];if(r){const hand=sim.renderHands?.[i]||add(sim.p,mul(unit(sub(r.anchor,sim.p)),1.3));lines.push({a:hand,b:r.anchor,color:sim.customWeb});geometry.limb(hand,r.anchor,.035,sim.customWeb);if(sim.hookFlash[i]>0){geometry.sphere(hand.x,hand.y,hand.z,.24,PALETTE.glow);geometry.sphere(r.anchor.x,r.anchor.y,r.anchor.z,.65,PALETTE.glow);}geometry.sphere(r.anchor.x,r.anchor.y,r.anchor.z,.4,PALETTE.white);}}
 for(const s of sim.shots){if(s.kind)geometry.box(s.p.x,s.p.y,s.p.z,s.kind==='car'?4:1.8,1.4,s.kind==='car'?2.4:1.4,s.color);else geometry.sphere(s.p.x,s.p.y,s.p.z,s.r,s.color);if(!s.enemy)lines.push({a:s.p,b:sub(s.p,mul(s.v,.045)),color:PALETTE.web});}for(const p of sim.particles)geometry.box(p.p.x,p.p.y,p.p.z,.18,.18,.18,p.color);
 if(photoMode)updateCamera(delta);renderer.environment=sim.environment;renderer.render(activeMesh,geometry,lines,camera,cameraTarget);drawAnchors();drawShopLabels();requestAnimationFrame(frame);}
features=installFeatures(sim,canvas,{skill:action=>triggerAction(action),toast,photo:on=>{photoMode=on;},freeze:keep=>{const ropes=sim.ropes,climbing=sim.climbing;paused=true;running=false;clearInput();if(keep){sim.ropes=ropes;sim.climbing=climbing;}},resume:()=>{paused=false;running=started;clearInput();},resetCamera:()=>{syncScene();yaw=0;camera=add(sim.p,V(0,8,18));cameraTarget=add(sim.p,V(0,1.4,0));}});
updateHUD();drawMap($('radar'));requestAnimationFrame(frame);
window.spiderGame={getState:()=>({dimension:3,scene:sim.interior?.shop.name||'城市',character:sim.character,style:sim.style,weather:sim.weather,climbing:!!sim.climbing,visitedShops:sim.visited.size,position:{...sim.p},health:sim.hp,settings:{...sim.options},resting:sim.resting,hanging:!!sim.hanging,citizens:sim.options.citizens?sim.civilians.length:0,boundEnemies:sim.targets().filter(b=>b.bound>0).map(b=>({name:b.name,seconds:b.bound})),swinging:sim.ropes.filter(Boolean).length,bosses:world.bosses.map(b=>({name:b.name,hp:b.hp,dead:b.dead}))})};
