import {V,add,sub,mul,length,unit,clamp,mix,color,Geometry,Renderer} from './engine3d.js?v=20261001c';
import {createWorld,Simulation,makeHero,makeBoss,makeCityLife,PALETTE} from './world3d.js?v=20261001c';
const $=id=>document.getElementById(id),canvas=$('game'),world=createWorld(),sim=new Simulation(world);
let renderer;
try{renderer=new Renderer(canvas);}catch(e){$('error').hidden=false;$('error').textContent=e.message;$('start').disabled=true;$('start').textContent='3D 画面无法启动';throw e;}
const city=renderer.upload(world.geometry);world.geometry.data=[];
const keyboard={},held=new Map(),pulse={};let stick={x:0,y:0},stickPointer=null,lookPointer=null,lookLast=null;
let started=false,running=false,paused=false,yaw=0,pitch=.21,last=0,toastTimer=0,hudTimer=0,radarTimer=0;
let camera=add(sim.p,V(0,10,22)),cameraTarget=add(sim.p,V(0,1.5,0));let hookTipShown=false;
const input=()=>({forward:clamp((keyboard.w?1:0)-(keyboard.s?1:0)-stick.y,-1,1),right:clamp((keyboard.d?1:0)-(keyboard.a?1:0)+stick.x,-1,1),jump:!!keyboard.jump||hasHeld('jump'),webLeft:!!keyboard.q||hasHeld('webLeft'),webRight:!!keyboard.e||hasHeld('webRight'),attack:!!keyboard.f||hasHeld('attack')});
const hasHeld=k=>[...held.values()].includes(k)||(pulse[k]||0)>performance.now();
function triggerAction(action){if(!running||!action)return;const now=performance.now();pulse[action]=now+(action==='webLeft'||action==='webRight'?140:100);if(action==='webLeft'||action==='webRight'){const side=action==='webLeft'?0:1;if(!sim.ropes[side])sim.attach(side,yaw);sim.previousHook[side]=true;}else if(action==='attack')sim.attack();}
function toast(msg,seconds=4){$('toast').textContent=msg;$('toast').style.opacity=1;toastTimer=seconds;}
function clearInput(){for(const k of Object.keys(keyboard))keyboard[k]=false;held.clear();for(const k of Object.keys(pulse))delete pulse[k];stick={x:0,y:0};$('knob').style.transform='';stickPointer=null;lookPointer=null;sim.resetInput();for(const b of document.querySelectorAll('.held'))b.classList.remove('held');}
function start(){if(!started){started=true;toast('按住右手蛛丝试试！拖动画面可以转动镜头。',7);}running=true;paused=false;$('overlay').hidden=true;$('pause').textContent='Ⅱ';clearInput();}
$('start').onclick=start;
function pause(){if(!started)return;paused=!paused;running=!paused;clearInput();$('overlay').hidden=!paused;$('pause').textContent=paused?'▶':'Ⅱ';$('start').textContent='继续飞行';}
$('pause').onclick=pause;$('help').onclick=()=>{if(!started)return;paused=false;pause();};
function closeMap(){ $('mapOverlay').hidden=true;paused=false;running=started;clearInput();}
$('mapButton').onclick=()=>{if(!started)return;paused=true;running=false;clearInput();$('mapOverlay').hidden=false;drawMap($('cityMap'),true);renderPlaces();};$('closeMap').onclick=closeMap;
function renderPlaces(){const p=$('mapPlaces');p.replaceChildren();world.districts.forEach((d,i)=>{const b=world.bosses[i-1],button=document.createElement('button');button.innerHTML='<span>'+d.name+'</span><small>'+(b?(b.dead?'已击败 · 再次挑战':b.name+' · 前往挑战'):'安全起点 · 练习飞行')+'</small>';button.onclick=()=>{sim.teleport(i);yaw=0;pitch=.21;camera=add(sim.p,V(0,10,22));cameraTarget=add(sim.p,V(0,1.5,0));closeMap();};p.appendChild(button);});}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','q','e','f',' ','arrowleft','arrowright','arrowup','arrowdown'].includes(k)){e.preventDefault();keyboard[k===' '?'jump':k]=true;if(!e.repeat)triggerAction(({q:'webLeft',e:'webRight',f:'attack',' ':'jump'})[k]);}if(e.key==='Escape'){if(!$('mapOverlay').hidden)closeMap();else pause();}});
addEventListener('keyup',e=>{keyboard[e.key===' '?'jump':e.key.toLowerCase()]=false;});
addEventListener('blur',()=>{clearInput();if(started&&running)pause();});
for(const btn of document.querySelectorAll('[data-action]')){btn.addEventListener('pointerdown',e=>{e.preventDefault();btn.setPointerCapture(e.pointerId);held.set(e.pointerId,btn.dataset.action);triggerAction(btn.dataset.action);btn.classList.add('held');});const up=e=>{held.delete(e.pointerId);if(!hasHeld(btn.dataset.action))btn.classList.remove('held');};btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);btn.addEventListener('lostpointercapture',up);}
const stickEl=$('stick');function moveStick(e){const r=stickEl.getBoundingClientRect(),radius=r.width*.35,dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,dist=Math.hypot(dx,dy),scale=dist>radius?radius/dist:1;stick={x:dx*scale/radius,y:dy*scale/radius};$('knob').style.transform='translate('+dx*scale+'px,'+dy*scale+'px)';}
stickEl.addEventListener('pointerdown',e=>{if(stickPointer!==null)return;e.preventDefault();stickPointer=e.pointerId;stickEl.setPointerCapture(e.pointerId);moveStick(e);});stickEl.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)moveStick(e);});function releaseStick(e){if(e.pointerId!==stickPointer)return;stickPointer=null;stick={x:0,y:0};$('knob').style.transform='';}stickEl.addEventListener('pointerup',releaseStick);stickEl.addEventListener('pointercancel',releaseStick);stickEl.addEventListener('lostpointercapture',releaseStick);
canvas.addEventListener('pointerdown',e=>{if(!running||lookPointer!==null)return;lookPointer=e.pointerId;lookLast={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer||!running)return;yaw-=(e.clientX-lookLast.x)*.005;pitch=clamp(pitch+(e.clientY-lookLast.y)*.004,-.12,.9);lookLast={x:e.clientX,y:e.clientY};$('lookHint').style.opacity='.2';});function releaseLook(e){if(e.pointerId===lookPointer)lookPointer=null;}canvas.addEventListener('pointerup',releaseLook);canvas.addEventListener('pointercancel',releaseLook);canvas.addEventListener('lostpointercapture',releaseLook);canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();running=false;clearInput();$('error').hidden=false;$('error').textContent='3D 画面已中断，请刷新页面后继续。';$('overlay').hidden=false;$('start').disabled=true;});canvas.addEventListener('webglcontextrestored',()=>location.reload());
addEventListener('resize',()=>renderer.resize());
function rayBuilding(origin,end,b){const dir=sub(end,origin);let min=0,max=1;for(const [axis,lo,hi] of [['x',b.x-b.w/2-.8,b.x+b.w/2+.8],['y',0,b.h+1.5],['z',b.z-b.d/2-.8,b.z+b.d/2+.8]]){if(Math.abs(dir[axis])<.0001){if(origin[axis]<lo||origin[axis]>hi)return null;}else{let t1=(lo-origin[axis])/dir[axis],t2=(hi-origin[axis])/dir[axis];if(t1>t2)[t1,t2]=[t2,t1];min=Math.max(min,t1);max=Math.min(max,t2);if(min>max)return null;}}return min;}
function updateCamera(dt){const forward=V(-Math.sin(yaw),0,-Math.cos(yaw)),speed=Math.hypot(sim.v.x,sim.v.z),distance=16.5+Math.min(speed*.1,9);const target=add(sim.p,V(0,1.4,0));const desired=add(sim.p,add(mul(forward,-distance*Math.cos(pitch)),V(0,3.5+distance*Math.sin(pitch),0)));cameraTarget=mix(cameraTarget,target,1-Math.exp(-10*dt));camera=mix(camera,desired,1-Math.exp(-11*dt));let closest=1;for(const b of world.buildings){const t=rayBuilding(cameraTarget,camera,b);if(t!==null)closest=Math.min(closest,t);}if(closest<1)camera=add(cameraTarget,mul(sub(camera,cameraTarget),Math.max(.08,closest-.03)));}
function drawMap(c,full=false){const ctx=c.getContext('2d'),w=c.width,h=c.height,s=Math.min(w,h)/1250,centerX=w/2,centerY=h/2;const xy=p=>({x:centerX+p.x*s,y:centerY+p.z*s});ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1b2f';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1c3b4d';ctx.lineWidth=1;for(let i=-5;i<=5;i++){ctx.beginPath();ctx.moveTo(centerX+i*110*s,centerY-600*s);ctx.lineTo(centerX+i*110*s,centerY+600*s);ctx.stroke();ctx.beginPath();ctx.moveTo(centerX-600*s,centerY+i*110*s);ctx.lineTo(centerX+600*s,centerY+i*110*s);ctx.stroke();}ctx.fillStyle='#29445a';for(const b of world.buildings){const p=xy(b);ctx.fillRect(p.x-b.w*s/2,p.y-b.d*s/2,b.w*s,b.d*s);}world.bosses.forEach((b,i)=>{const p=xy(b.p);ctx.fillStyle=b.dead?'#4c6d80':['#eabf9b','#65e2ff','#adeb8b'][i];ctx.beginPath();ctx.arc(p.x,p.y,full?5:3,0,Math.PI*2);ctx.fill();if(full){ctx.font='12px system-ui';ctx.fillText(b.name,p.x+9,p.y+4);}});const p=xy(sim.p);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(-yaw);ctx.fillStyle='#ff536b';ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(5,5);ctx.lineTo(0,2);ctx.lineTo(-5,5);ctx.closePath();ctx.fill();ctx.restore();if(full){ctx.font='11px system-ui';ctx.fillStyle='#adc2d5';ctx.fillText('红色箭头是你的位置',14,h-14);}}
function updateHUD(){for(let i=0;i<2;i++){const button=document.querySelector('[data-action="'+(i===0?'webLeft':'webRight')+'"]');button.classList.toggle('connected',!!sim.ropes[i]);button.querySelector('small').textContent=sim.ropes[i]?'已挂住 · 松手飞出':(i===0?'Q':'E')+' · 按住';} $('health').style.width=sim.hp+'%';$('hp').textContent=Math.ceil(sim.hp);$('count').textContent='Boss '+world.bosses.filter(b=>b.dead).length+' / 3';$('speed').querySelector('b').textContent=Math.round(Math.hypot(sim.v.x,sim.v.z));const nearest=world.districts.reduce((a,b)=>length(sub(sim.p,V(a.b.x,a.b.h,a.b.z)))<length(sub(sim.p,V(b.b.x,b.b.h,b.b.z)))?a:b);$('location').textContent=nearest.name;const boss=world.bosses.filter(b=>!b.dead&&length(sub(b.p,sim.p))<165).sort((a,b)=>length(sub(a.p,sim.p))-length(sub(b.p,sim.p)))[0];$('bossHUD').hidden=!boss;if(boss){$('bossName').textContent=boss.name;$('bossHealth').style.width=boss.hp/boss.max*100+'%';$('warning').textContent=boss.warning>0?['准备冲锋 · 跳跃躲开','蓄力闪电 · 保持移动','准备投弹 · 离开落点'][boss.type]:'靠近后按蛛丝攻击';}}
function drawAnchors(){for(let i=0;i<2;i++){const el=$(i===0?'anchorLeft':'anchorRight');if(!started||!running){el.hidden=true;continue;}const candidate=sim.ropes[i]?{anchor:sim.ropes[i].anchor}:sim.selectHook(i,yaw);const screen=candidate?renderer.project(candidate.anchor):null;el.hidden=!(screen&&screen.visible);if(screen?.visible){el.style.left=screen.x+'px';el.style.top=screen.y+'px';el.style.borderColor=sim.ropes[i]?'#ffffff':'#8beaffaa';}}}
let clock=0;
function frame(t){const delta=Math.min((t-last)/1000,.05);last=t;clock+=delta;if(running){if(keyboard.arrowleft)yaw+=delta*1.5;if(keyboard.arrowright)yaw-=delta*1.5;if(keyboard.arrowup)pitch=clamp(pitch-delta*.8,-.12,.9);if(keyboard.arrowdown)pitch=clamp(pitch+delta*.8,-.12,.9);let left=delta;const state=input();while(left>0){const dt=Math.min(left,1/120);sim.update(dt,state,yaw);left-=dt;}updateCamera(delta);if(sim.ropes.some(Boolean)&&!hookTipShown){toast('挂住了！推动摇杆助推，松开蛛丝借惯性飞出去。',5);hookTipShown=true;}if(sim.messages.length){toast(sim.messages[sim.messages.length-1]);sim.messages=[];}if(toastTimer>0){toastTimer-=delta;if(toastTimer<=0)$('toast').style.opacity=0;}}
 const geometry=new Geometry(),lines=[];makeCityLife(geometry,sim.time,sim.p);if(sim.inv<=0||Math.floor(clock*12)%2===0)makeHero(geometry,sim);for(const b of world.bosses)if(length(sub(b.p,sim.p))<400)makeBoss(geometry,b);
 for(let i=0;i<2;i++){const r=sim.ropes[i];if(r){const hand=add(sim.p,mul(unit(sub(r.anchor,sim.p)),1.3));lines.push({a:hand,b:r.anchor,color:PALETTE.web});geometry.limb(hand,r.anchor,.035,PALETTE.white);if(sim.hookFlash[i]>0){geometry.sphere(hand.x,hand.y,hand.z,.24,PALETTE.glow);geometry.sphere(r.anchor.x,r.anchor.y,r.anchor.z,.65,PALETTE.glow);}geometry.sphere(r.anchor.x,r.anchor.y,r.anchor.z,.4,PALETTE.white);}}
 for(const s of sim.shots){geometry.sphere(s.p.x,s.p.y,s.p.z,s.r,s.color);if(!s.enemy)lines.push({a:s.p,b:sub(s.p,mul(s.v,.045)),color:PALETTE.web});}for(const p of sim.particles)geometry.box(p.p.x,p.p.y,p.p.z,.18,.18,.18,p.color);
 renderer.render(city,geometry,lines,camera,cameraTarget);drawAnchors();hudTimer+=delta;radarTimer+=delta;if(hudTimer>.1){updateHUD();hudTimer=0;}if(radarTimer>.2){drawMap($('radar'));radarTimer=0;}requestAnimationFrame(frame);}
updateHUD();drawMap($('radar'));requestAnimationFrame(frame);
window.spiderGame={getState:()=>({dimension:3,position:{...sim.p},health:sim.hp,swinging:sim.ropes.filter(Boolean).length,bosses:world.bosses.map(b=>({name:b.name,hp:b.hp,dead:b.dead}))})};
