import{DEFAULT_SETTINGS,DEFAULT_KEYS,KEY_ACTIONS,normalizeSettings,normalizeKeys,presetSettings,applySettings}from'./settings-model.js?v=20261006savefix';
export{DEFAULT_KEYS};
const GROUPS=[['蛛丝移动',[['swingAssist','蛛丝辅助摆动','0：大惯性 · 10：强辅助'],['autoAttach','蛛丝自动吸附建筑','关闭后对准挂点发射'],['trickSlow','空中特技自动慢动作','空翻与旋转时放慢时间'],['autoClimb','墙面自动攀爬','关闭后按攀墙键贴墙'],['zipAssist','蛛丝弹射助力','关闭后只拉向挂点，不提供高速助推'],['propPull','蛛丝拉拽物体','垃圾桶、广告牌与车辆'],['doubleWeb','空中二段蛛丝','空中允许追加或更换蛛丝']]],['城市环境',[['dayCycle','昼夜循环'],['fixedTime','固定时间'],['randomWeather','随机天气'],['fixedWeather','固定天气'],['citizens','市民路人 AI','关闭后隐藏街上的普通市民'],['destruction','城市物理破坏效果','撞击碎片与墙面命中粒子；建筑保持完整']]],['事件与战斗',[['events','随机城市突发事件','可自由参与或忽略救援与居民冲突'],['combat','敌人战斗系统','关闭后隐藏敌人并停止所有战斗'],['sense','蜘蛛感应预警提示'],['damage','敌人攻击伤害','0：无伤害 · 5：正常 · 10：双倍'],['enemySpawn','敌人刷新','关闭后不产生新的打手，不重置已击败 Boss']]],['角色外观',[['suitPowers','战衣特殊技能效果'],['unlockSuits','一键解锁全部战衣','关闭后依照已有风格分数解锁'],['idle','角色待机小动作']]],['画面与UI',[['photo','拍照模式'],['styleDisplay','空中特技分数显示'],['hud','HUD 界面','隐藏地图、提示与操作按钮；保留设置入口']]],['挑战',[['race','城市竞速挑战点'],['trickChallenge','特技评分挑战'],['bossChallenge','可选 BOSS 挑战']]],['控制',[['sensitivity','镜头灵敏度','0：最慢 · 10：最快'],['invertY','反转 Y 轴']]]];
export function installSettings(sim,keys,callbacks){const $=id=>document.getElementById(id);let selected=0,capture=null;
 try{const saved=JSON.parse(localStorage.getItem('spider-neon-settings')||'null');if(saved){applySettings(sim,saved.options);Object.assign(keys,normalizeKeys(saved.keys));if(['easy','normal','hard'].includes(saved.difficulty))sim.difficulty=saved.difficulty;sim.maskOff=!!saved.maskOff;const validColor=v=>Array.isArray(v)&&v.length===3&&v.every(n=>Number.isFinite(n)&&n>=0&&n<=3);if(validColor(saved.web))sim.customWeb=saved.web;sim.customSuitColor=validColor(saved.suit)?saved.suit:null;}}catch{}applySettings(sim,sim.options||DEFAULT_SETTINGS);
 function save(){try{localStorage.setItem('spider-neon-settings',JSON.stringify({options:sim.options,keys,difficulty:sim.difficulty,maskOff:sim.maskOff,web:sim.customWeb,suit:sim.customSuitColor}));}catch{callbacks.toast('浏览器没有保存空间，当前设置仍然生效。');}}
 const audio=new CityAudio(sim);function apply(next){applySettings(sim,next);syncVisibility();save();audio.apply();}
 const nav=$('settingsTabs'),pages=$('settingsPages');GROUPS.forEach(([title,fields],i)=>{const tab=document.createElement('button');tab.id='settingsTab'+i;tab.setAttribute('role','tab');tab.setAttribute('aria-controls','settingsPage'+i);tab.textContent=title;tab.onclick=()=>select(i);nav.appendChild(tab);const page=document.createElement('section');page.id='settingsPage'+i;page.setAttribute('role','tabpanel');page.setAttribute('aria-labelledby',tab.id);const h=document.createElement('h3');h.textContent=title;page.appendChild(h);for(const [key,label,hint]of fields){const row=document.createElement('label');row.className='option-row';const text=document.createElement('span');const strong=document.createElement('b');strong.textContent=label;text.appendChild(strong);if(hint){const small=document.createElement('small');small.textContent=hint;text.appendChild(small);}row.appendChild(text);let control;if(key==='fixedTime'||key==='fixedWeather'){control=document.createElement('select');const choices=key==='fixedTime'?{day:'白天',dusk:'黄昏',night:'夜晚'}:{clear:'晴天',rain:'雨天',fog:'大雾'};for(const [value,name]of Object.entries(choices)){const o=document.createElement('option');o.value=value;o.textContent=name;control.appendChild(o);}}else{control=document.createElement('input');control.type=typeof DEFAULT_SETTINGS[key]==='boolean'?'checkbox':'range';if(control.type==='range'){control.min=0;control.max=10;control.step=1;const out=document.createElement('output');out.id='value-'+key;row.appendChild(out);}}control.id='opt-'+key;control.setAttribute('aria-label',label);control.oninput=()=>{const value=control.type==='checkbox'?control.checked:control.type==='range'?Number(control.value):control.value;apply({...sim.options,[key]:value});refresh();};row.appendChild(control);page.appendChild(row);}pages.appendChild(page);});
 $('settingsPage3').appendChild($('appearanceControls'));$('settingsPage6').appendChild($('controlExtras'));$('controlExtras').hidden=false;$('appearanceControls').hidden=false;
 function select(i){selected=i;for(let j=0;j<GROUPS.length;j++){$('settingsPage'+j).hidden=i!==j;$('settingsTab'+j).setAttribute('aria-selected',String(i===j));$('settingsTab'+j).tabIndex=i===j?0:-1;}}
 nav.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();select((selected+(['ArrowLeft','ArrowUp'].includes(e.key)?6:1))%7);$('settingsTab'+selected).focus();};
 function refresh(){const toHex=c=>'#'+c.map(n=>Math.round(Math.max(0,Math.min(1,n))*255).toString(16).padStart(2,'0')).join('');$('webColor').value=toHex(sim.customWeb);$('suitColor').value=toHex(sim.customSuitColor||[.933,.208,.31]);for(const [,fields]of GROUPS)for(const [key]of fields){const c=$('opt-'+key);if(c.type==='checkbox')c.checked=sim.options[key];else c.value=sim.options[key];if($('value-'+key))$('value-'+key).textContent=sim.options[key];} $('opt-fixedTime').disabled=sim.options.dayCycle;$('opt-fixedWeather').disabled=sim.options.randomWeather;$('difficulty').value=sim.difficulty;$('maskOff').checked=sim.maskOff;for(const kind of ['music','ambient','effects']){$(kind+'Volume').value=sim.options[kind+'Volume'];$(kind+'Value').textContent=sim.options[kind+'Volume']+'%';}select(selected);renderKeys();}
 function renderKeys(){$('keyFields').replaceChildren();for(const [action,[label]]of Object.entries(KEY_ACTIONS)){const row=document.createElement('div');row.className='key-row';const span=document.createElement('span');span.textContent=label;const b=document.createElement('button');b.textContent=capture===action?'按下新按键…':keyName(keys[action]);b.setAttribute('aria-label','修改'+label+'按键');b.onclick=()=>{capture=action;renderKeys();};row.append(span,b);$('keyFields').appendChild(row);}}
 document.addEventListener('keydown',e=>{if(!capture)return;e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape'){capture=null;renderKeys();return;}const k=e.key.toLowerCase(),valid=/^[a-z0-9 ]$/.test(k)||['shift','control','alt','arrowleft','arrowright','arrowup','arrowdown'].includes(k);if(!valid||Object.entries(keys).some(([a,v])=>a!==capture&&v===k)){callbacks.toast('这个按键不可用或已经占用，请选另一个；Esc 取消。');return;}keys[capture]=k;capture=null;save();renderKeys();callbacks.labels?.();},true);
 $('editKeys').onclick=()=>{$('keyFields').hidden=!$('keyFields').hidden;capture=null;renderKeys();};$('keyFields').hidden=true;
 $('resetSettings').onclick=()=>{capture=null;Object.assign(keys,DEFAULT_KEYS);sim.difficulty='normal';sim.maskOff=false;sim.customSuitColor=null;apply(DEFAULT_SETTINGS);refresh();callbacks.labels?.();callbacks.toast('已恢复完整沙盒默认设置。');};
 for(const [id,name]of [['tourPreset','tour'],['sandboxPreset','sandbox']])$(id).onclick=()=>{capture=null;apply(presetSettings(name));refresh();callbacks.toast(name==='tour'?'纯观光：固定夜晚，无敌人和事件。':'完整沙盒：自由探索与战斗已开启。');};
 $('difficulty').onchange=()=>{sim.difficulty=$('difficulty').value;save();};$('maskOff').onchange=()=>{sim.maskOff=$('maskOff').checked;save();};$('webColor').oninput=()=>{sim.customWeb=hexColor($('webColor').value);save();};$('suitColor').oninput=()=>{sim.customSuitColor=hexColor($('suitColor').value);save();};
 for(const kind of ['music','ambient','effects'])$(kind+'Volume').oninput=()=>{apply({...sim.options,[kind+'Volume']:Number($(kind+'Volume').value)});$(kind+'Value').textContent=sim.options[kind+'Volume']+'%';};
 function syncVisibility(){document.body.classList.toggle('clean-hud',!sim.options.hud);$('styleHUD').classList.toggle('option-hidden',!sim.options.styleDisplay);$('photoButton').hidden=!sim.options.photo;$('startRace').disabled=!sim.options.race;$('startStunts').disabled=!sim.options.trickChallenge;}
 syncVisibility();select(0);refresh();
 return{open:refresh,save,disposeCapture(){capture=null;},syncVisibility,audio};
}
function keyName(k){return k===' '?'空格':{shift:'Shift',control:'Ctrl',alt:'Alt',arrowleft:'←',arrowright:'→',arrowup:'↑',arrowdown:'↓'}[k]||k.toUpperCase();}
function hexColor(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255);}
// Original synthesized ambience: no downloaded music or audio assets.
class CityAudio{
 constructor(sim){this.sim=sim;this.ctx=null;this.timer=0;this.note=0;document.addEventListener('pointerdown',()=>this.start(),{once:true});document.addEventListener('keydown',()=>this.start(),{once:true});document.addEventListener('visibilitychange',()=>{if(!this.ctx)return;if(document.hidden)this.ctx.suspend();else this.ctx.resume().catch(()=>{});});}
 start(){try{if(this.ctx){this.ctx.resume().catch(()=>{});return;}const A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.ctx=new A();this.bus={};for(const kind of ['music','ambient','effects']){const g=this.ctx.createGain();g.connect(this.ctx.destination);this.bus[kind]=g;}const noise=this.ctx.createBuffer(1,this.ctx.sampleRate*3,this.ctx.sampleRate),data=noise.getChannelData(0);let v=0;for(let i=0;i<data.length;i++){v=.985*v+.015*(Math.random()*2-1);data[i]=v;}const src=this.ctx.createBufferSource();src.buffer=noise;src.loop=true;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;src.connect(filter);filter.connect(this.bus.ambient);src.start();this.apply();}catch{}}
 apply(){if(!this.ctx)return;for(const kind of ['music','ambient','effects'])this.bus[kind].gain.setTargetAtTime(this.sim.options[kind+'Volume']/100*(kind==='ambient'?.18:.12),this.ctx.currentTime,.05);}
 tone(kind,freq,time=.2,type='sine'){if(!this.ctx||this.ctx.state!=='running'||!this.sim.options[kind+'Volume'])return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),t=this.ctx.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.35,t+.025);g.gain.exponentialRampToValueAtTime(.001,t+time);o.connect(g);g.connect(this.bus[kind]);o.start();o.stop(t+time+.02);}
 effect(action){this.start();this.tone('effects',action==='bind'?700:action==='attack'?520:action==='dodge'?300:action==='interact'?880:450,.13,'triangle');}
 tick(dt,running){if(!running||!this.ctx)return;this.timer+=dt;if(this.timer>1.2){this.timer=0;this.tone('music',[196,246.94,293.66,392,329.63,293.66,246.94,220][this.note++%8],.95);}}
}
