import {V,add,sub,mul,dot,length,unit,clamp,color,Geometry} from './engine3d.js';
export const PALETTE={red:color('#ee354f'),blue:color('#2058aa'),white:color('#f0faff'),ink:color('#142139'),web:color('#bcefff'),cyan:color('#58d7ee')};
export function createWorld(){let seed=48391;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const buildings=[],geometry=new Geometry(),range=620;
 geometry.box(0,-1,0,1400,2,1400,color('#192b35'));geometry.box(0,-3,0,2400,2,2400,color('#12445b'));
 for(let i=-5;i<=5;i++){geometry.box(i*110,.03,0,29,.08,1220,color('#233044'));geometry.box(0,.04,i*110,1220,.08,29,color('#233044'));for(let k=-590;k<=590;k+=22){geometry.box(i*110,.1,k,.35,.05,7,color('#778780'));geometry.box(k,.1,i*110,7,.05,.35,color('#778780'));}}
 for(let i=-5;i<5;i++)for(let j=-5;j<5;j++){const x=(i+.5)*110,z=(j+.5)*110;const park=(i===-1&&j===0)||(i===0&&j===0)||(i===3&&j===-1);if(park){geometry.box(x,.2,z,76,.3,76,color('#254a3f'));for(let t=0;t<6;t++){const tx=x+(rnd()-.5)*58,tz=z+(rnd()-.5)*58;geometry.box(tx,3,tz,1,6,1,color('#635444'));geometry.sphere(tx,7,tz,4,color('#397363'),1,1.4,1);}continue;}
 const b={x,z,w:62+rnd()*13,d:62+rnd()*13,h:24+rnd()*78,i,j};if(i===0&&j===3){b.h=36;b.w=b.d=76;}if((i===2&&j===1)||(i===-3&&j===-3)||(i===1&&j===-4)){b.h=[42,54,78][i===2?0:i===-3?1:2];b.w=b.d=78;}buildings.push(b);
 geometry.box(x,.2,z,b.w+7,.4,b.d+7,color('#3c4857'));const col=[color('#314359'),color('#344e61'),color('#405065'),color('#2c4156')][Math.floor(rnd()*4)];geometry.box(x,b.h/2,z,b.w,b.h,b.d,col);geometry.box(x,b.h+.45,z,b.w+1.6,.9,b.d+1.6,color('#597583'));
 // Facade windows are flat triangles, merged into the city mesh.
 const warm=color('#d7b76f'),cool=color('#6dabb8');for(let y=6;y<b.h-3;y+=6){for(let a=-b.w/2+6;a<b.w/2-3;a+=7){if(rnd()<.28)continue;const c=rnd()>.45?warm:cool;const zz=b.z+b.d/2+.02;geometry.quad(V(x+a-1.2,y-1.6,zz),V(x+a+1.2,y-1.6,zz),V(x+a+1.2,y+1.6,zz),V(x+a-1.2,y+1.6,zz),V(0,0,1),c);const z2=b.z-b.d/2-.02;geometry.quad(V(x+a+1.2,y-1.6,z2),V(x+a-1.2,y-1.6,z2),V(x+a-1.2,y+1.6,z2),V(x+a+1.2,y+1.6,z2),V(0,0,-1),c);}for(let a=-b.d/2+6;a<b.d/2-3;a+=7){if(rnd()<.3)continue;const c=rnd()>.6?warm:cool;const xx=b.x+b.w/2+.02;geometry.quad(V(xx,y-1.6,z+a+1.2),V(xx,y-1.6,z+a-1.2),V(xx,y+1.6,z+a-1.2),V(xx,y+1.6,z+a+1.2),V(1,0,0),c);const x2=b.x-b.w/2-.02;geometry.quad(V(x2,y-1.6,z+a-1.2),V(x2,y-1.6,z+a+1.2),V(x2,y+1.6,z+a+1.2),V(x2,y+1.6,z+a-1.2),V(-1,0,0),c);}}
 geometry.box(x-15,b.h+2,z+12,8,4,10,color('#52616e'));geometry.box(x+18,b.h+1.5,z+12,9,3,7,color('#607986'));if(rnd()>.6){geometry.box(x+18,b.h+8,z-18,.4,16,.4,color('#819ca3'));geometry.sphere(x+18,b.h+16,z-18,.5,PALETTE.red);} }
 const find=(i,j)=>buildings.find(b=>b.i===i&&b.j===j);const spawn=find(0,3);const districts=[{name:'河岸楼顶',tag:'安全起点',b:spawn},{name:'工业城区',tag:'犀牛人',b:find(2,1)},{name:'霓虹街区',tag:'电光人',b:find(-3,-3)},{name:'中央高楼',tag:'绿魔',b:find(1,-4)}];
 const bosses=districts.slice(1).map((d,type)=>({name:d.tag,type,base:d.b,p:V(d.b.x,d.b.h+3.5,d.b.z),hp:[260,220,240][type],max:[260,220,240][type],dead:false,time:0,cool:2.6,warning:0,charge:0,stun:0,color:[color('#b0b5c4'),color('#64edff'),color('#a0db73')][type]}));
 return{buildings,geometry,spawn,districts,bosses,range};}
export class Simulation {
 constructor(world){this.world=world;const s=world.spawn;this.p=V(s.x,s.h+2.5,s.z);this.v=V();this.facing=0;this.hp=100;this.inv=0;this.grounded=true;this.jumpLock=false;this.ropes=[null,null];this.shots=[];this.particles=[];this.attackCool=0;this.groundTime=0;this.time=0;this.checkpoint=s;this.messages=[];this.previousHook=[false,false];}
 notify(text){this.messages.push(text);}
 resetInput(){this.ropes=[null,null];this.previousHook=[false,false];this.jumpLock=false;}
 candidates(yaw){const forward=V(-Math.sin(yaw),0,-Math.cos(yaw)),right=V(Math.cos(yaw),0,-Math.sin(yaw));const result=[];for(const b of this.world.buildings)for(const sx of [-1,1])for(const sz of [-1,1]){const a=V(b.x+sx*(b.w/2-2),b.h+3.3,b.z+sz*(b.d/2-2)),delta=sub(a,this.p),d=length(delta),flat=unit(V(delta.x,0,delta.z)),front=dot(flat,forward);if(d<18||d>190||a.y<this.p.y+1||front<-.15)continue;result.push({anchor:a,d,front,side:dot(flat,right),building:b});}return result;}
 selectHook(side,yaw){const list=this.candidates(yaw),sign=side===0?-1:1,other=this.ropes[1-side];list.sort((a,b)=>score(a)-score(b));function score(a){return a.d*(1+(1-a.front)*.65)+Math.max(0,-a.side*sign)*55+(other&&length(sub(a.anchor,other.anchor))<8?50:0);}return list[0]||null;}
 attach(side,yaw){const c=this.selectHook(side,yaw);if(!c){this.notify('前方没有合适的楼顶，转动镜头再试试。');return;}this.ropes[side]={anchor:c.anchor,length:c.d};if(this.grounded){this.v.y=14;this.v.x-=Math.sin(yaw)*12;this.v.z-=Math.cos(yaw)*12;this.grounded=false;}this.burst(c.anchor,PALETTE.web,9);}
 attack(){if(this.attackCool>0)return;const nearby=this.world.bosses.filter(b=>!b.dead&&length(sub(b.p,this.p))<150).sort((a,b)=>length(sub(a.p,this.p))-length(sub(b.p,this.p)));const target=nearby[0];const direction=target?unit(sub(target.p,this.p)):V(-Math.sin(this.facing),.02,-Math.cos(this.facing));this.shots.push({p:add(this.p,V(0,.8,0)),v:mul(direction,105),life:1.8,enemy:false,r:.5,color:PALETTE.white,damage:14});this.attackCool=.25;}
 burst(p,c,n=10){for(let i=0;i<n;i++)this.particles.push({p:{...p},v:V((Math.random()-.5)*14,Math.random()*12,(Math.random()-.5)*14),life:.5+Math.random()*.4,color:c});}
 damage(n){if(this.inv>0)return;this.hp=Math.max(0,this.hp-n);this.inv=1;this.burst(this.p,PALETTE.red,12);if(this.hp===0)this.respawn();}
 respawn(){const b=this.checkpoint;this.p=V(b.x-20,b.h+2.5,b.z+17);this.v=V();this.hp=100;this.inv=3;this.ropes=[null,null];this.shots=[];this.notify('回到安全楼顶，继续探索！');}
 teleport(index){const d=this.world.districts[index],b=d.b,boss=this.world.bosses[index-1];if(boss?.dead){boss.dead=false;boss.hp=boss.max;boss.cool=3;}this.p=V(b.x-22,b.h+2.5,b.z+23);this.v=V();this.grounded=true;this.inv=2;this.checkpoint=b;this.ropes=[null,null];this.shots=[];this.notify('已到达'+d.name);}
 update(dt,input,yaw){this.time+=dt;this.inv=Math.max(0,this.inv-dt);this.attackCool=Math.max(0,this.attackCool-dt);
 for(let i=0;i<2;i++){const held=i===0?input.webLeft:input.webRight;if(held&&!this.previousHook[i])this.attach(i,yaw);if(!held)this.ropes[i]=null;this.previousHook[i]=held;}
 const forward=V(-Math.sin(yaw),0,-Math.cos(yaw)),right=V(Math.cos(yaw),0,-Math.sin(yaw));let move=add(mul(forward,input.forward||0),mul(right,input.right||0));if(length(move)>1)move=unit(move);const active=this.ropes.filter(Boolean),air=!this.grounded;
 if(length(move)>.1)this.facing=Math.atan2(-move.x,-move.z);
 const acceleration=this.grounded?105:active.length?35:21;this.v.x+=move.x*acceleration*dt;this.v.z+=move.z*acceleration*dt;const friction=this.grounded?5.6:.22;this.v.x*=Math.exp(-friction*dt);this.v.z*=Math.exp(-friction*dt);const speed=Math.hypot(this.v.x,this.v.z),limit=active.length?78:air?60:20;if(speed>limit){this.v.x*=limit/speed;this.v.z*=limit/speed;}
 if(input.jump&&!this.jumpLock){if(this.grounded){this.v.y=17;this.grounded=false;}else{const wall=this.world.buildings.find(b=>this.p.y<b.h+1&&Math.abs(this.p.x-b.x)<b.w/2+2&&Math.abs(this.p.z-b.z)<b.d/2+2);if(wall){this.v.y=18;this.v.x-=forward.x*7;this.v.z-=forward.z*7;this.burst(this.p,PALETTE.cyan,6);}}this.jumpLock=true;}if(!input.jump)this.jumpLock=false;
 this.v.y-=25*dt;for(const r of active){r.length=Math.max(9,r.length-8*dt);const n=unit(sub(r.anchor,this.p));this.v=add(this.v,mul(n,48*dt));}
 const before={...this.p};this.p=add(this.p,mul(this.v,dt));for(const r of active){const delta=sub(this.p,r.anchor),dist=length(delta);if(dist>r.length){const n=mul(delta,1/dist);this.p=add(r.anchor,mul(n,r.length));const out=dot(this.v,n);if(out>0)this.v=sub(this.v,mul(n,out));}}
 this.grounded=false;const radius=1.1,feet=1.6;
 for(const b of this.world.buildings){const dx=this.p.x-b.x,dz=this.p.z-b.z;if(Math.abs(dx)>b.w/2+radius||Math.abs(dz)>b.d/2+radius)continue;const top=b.h+.9+feet;
 if(before.y>=top-.2&&this.p.y<=top&&this.v.y<=0){this.p.y=top;this.v.y=0;this.grounded=true;if(!this.world.bosses.some(q=>q.base===b&&!q.dead))this.checkpoint=b;}
 else if(this.p.y<top-.1&&this.p.y>0){const overlapX=b.w/2+radius-Math.abs(dx),overlapZ=b.d/2+radius-Math.abs(dz);if(overlapX<overlapZ){this.p.x=b.x+Math.sign(dx||1)*(b.w/2+radius);this.v.x=0;}else{this.p.z=b.z+Math.sign(dz||1)*(b.d/2+radius);this.v.z=0;}if(input.jump)this.v.y=Math.max(this.v.y,13);}}
 if(this.p.y<feet){this.p.y=feet;this.v.y=0;this.grounded=true;}this.p.x=clamp(this.p.x,-590,590);this.p.z=clamp(this.p.z,-590,590);this.p.y=Math.min(this.p.y,260);
 if(this.grounded&&!active.length){this.groundTime+=dt;if(this.groundTime>3)this.hp=Math.min(100,this.hp+8*dt);}else this.groundTime=0;if(input.attack)this.attack();
 this.updateBosses(dt);for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];const old={...s.p};s.p=add(s.p,mul(s.v,dt));s.life-=dt;if(s.enemy){if(length(sub(s.p,this.p))<s.r+1.35){this.damage(s.damage);s.life=0;}}else{for(const b of this.world.bosses){if(!b.dead&&length(sub(s.p,b.p))<3.4){b.hp=Math.max(0,b.hp-s.damage);b.stun=.08;this.burst(s.p,PALETTE.web,8);s.life=0;if(b.hp===0){b.dead=true;this.burst(b.p,b.color,35);this.hp=Math.min(100,this.hp+30);const n=this.world.bosses.filter(q=>q.dead).length;this.notify(n===3?'三个 Boss 全部击败！继续在城市自由飞行。':'击败'+b.name+'！可以继续探索其他城区。');}break;}}}
 if(s.p.y<0)s.life=0;if(s.life<=0)this.shots.splice(i,1);}
 for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.p=add(p.p,mul(p.v,dt));p.v.y-=12*dt;p.life-=dt;if(p.life<=0)this.particles.splice(i,1);}}
 updateBosses(dt){for(const b of this.world.bosses){if(b.dead)continue;b.time+=dt;b.stun=Math.max(0,b.stun-dt);const base=b.base,near=length(sub(b.p,this.p))<165;
 if(b.type===1)b.p.y=base.h+8+Math.sin(b.time*1.5)*4;
 if(b.type===2){b.p.y=base.h+12+Math.sin(b.time)*5;b.p.x=base.x+Math.sin(b.time*.65)*18;b.p.z=base.z+Math.cos(b.time*.65)*18;}
 if(b.type===0&&b.charge>0){b.charge-=dt;b.p=add(b.p,mul(b.chargeDirection,32*dt));b.p.x=clamp(b.p.x,base.x-base.w/2+5,base.x+base.w/2-5);b.p.z=clamp(b.p.z,base.z-base.d/2+5,base.z+base.d/2-5);}
 if(!near)continue;if(length(sub(b.p,this.p))<(b.type===0?4.5:3))this.damage(16);
 if(b.warning>0){b.warning-=dt;if(b.warning<=0){const direction=unit(sub(this.p,b.p));if(b.type===0){b.charge=1;b.chargeDirection=unit(V(direction.x,0,direction.z));}
 const count=b.type===1?3:1;for(let i=0;i<count;i++){const angle=(i-(count-1)/2)*.15,c=Math.cos(angle),s=Math.sin(angle);const dir=V(direction.x*c-direction.z*s,direction.y,direction.x*s+direction.z*c);this.shots.push({p:add(b.p,V(0,1,0)),v:mul(dir,[29,40,32][b.type]),life:5,enemy:true,r:b.type===2?1.2:.7,color:b.color,damage:b.type===0?18:12,type:b.type});}b.cool=[3.6,3.2,2.8][b.type];}}
 else {b.cool-=dt;if(b.cool<=0&&b.stun===0){b.warning=.75;this.burst(b.p,b.color,5);}}}}
}
export function makeHero(g,sim){const p=sim.p,yaw=sim.facing,co=Math.cos(yaw),si=Math.sin(yaw);const transform=(x,y,z)=>V(p.x+x*co+z*si,p.y+y,p.z-x*si+z*co);const cube=(x,y,z,w,h,d,c)=>{const a=transform(x,y,z);g.box(a.x,a.y,a.z,w,h,d,c,yaw);};const sphere=(x,y,z,r,c,rx=1,ry=1,rz=1)=>{const a=transform(x,y,z);g.sphere(a.x,a.y,a.z,r,c,rx,ry,rz);};
 const running=sim.grounded&&Math.hypot(sim.v.x,sim.v.z)>2,swing=sim.ropes.some(Boolean),step=running?Math.sin(sim.time*12)*.6:swing?.3:.04;
 cube(0,.05,0,.85,1.05,.5,PALETTE.red);cube(0,-.5,0,.78,.25,.5,PALETTE.blue);sphere(0,1.03,0,.43,PALETTE.red,.95,1.15,.95);
 for(const side of [-1,1]){const hip=transform(side*.23,-.52,0),knee=transform(side*.28,-1,side*step),foot=transform(side*.3,-1.5,side*step*.6);g.limb(hip,knee,.19,PALETTE.blue);g.limb(knee,foot,.18,PALETTE.blue);cube(side*.3,-1.48,side*step*.6-.08,.38,.23,.6,PALETTE.red);const rope=sim.ropes[side<0?0:1],shoulder=transform(side*.48,.45,0),hand=rope?add(p,mul(unit(sub(rope.anchor,p)),1.45)):transform(side*.77,-.22,side*step*.45);g.limb(shoulder,hand,.16,PALETTE.red);g.sphere(hand.x,hand.y,hand.z,.2,PALETTE.red);cube(side*.18,1.03,-.385,.22,.22,.08,PALETTE.white);}
 cube(0,.12,-.28,.12,.25,.05,PALETTE.ink);cube(0,.2,.275,.19,.3,.035,PALETTE.ink);for(const side of [-1,1])for(let i=0;i<3;i++){const a=transform(side*.06,.15-i*.04,.29),b=transform(side*.28,.32-i*.15,.29);g.limb(a,b,.022,PALETTE.ink);}}
export function makeBoss(g,b){if(b.dead)return;const p=b.p,c=b.color,ink=PALETTE.ink;
 if(b.type===0){g.box(p.x,p.y,p.z,3.4,3.4,2.4,c);g.sphere(p.x,p.y+2.3,p.z-.2,1,c);g.cone(p.x,p.y+3,p.z-.6,.4,1.6,color('#eef1ec'));for(const s of [-1,1]){g.box(p.x+s*2.1,p.y,p.z,.9,2.7,1.4,c);g.box(p.x+s*.8,p.y-2,p.z,1.1,1.5,1.2,color('#6d7a91'));g.box(p.x+s*.4,p.y+2.3,p.z-1.05,.3,.2,.15,ink);}}
 else if(b.type===1){g.box(p.x,p.y,p.z,1.7,2.8,1,color('#164c73'));g.sphere(p.x,p.y+2,p.z,.7,c);for(const s of [-1,1]){g.limb(add(p,V(s*.8,1,0)),add(p,V(s*2.3,1.6,0)),.32,c);g.limb(add(p,V(s*.45,-1,0)),add(p,V(s*.65,-2.5,0)),.3,c);}g.box(p.x,p.y+.2,p.z-.53,.35,1.2,.1,c);for(let i=0;i<3;i++){const a=b.time*2+i*2.094;g.sphere(p.x+Math.cos(a)*3,p.y+Math.sin(a)*2,p.z+Math.sin(a)*3,.25,c);}}
 else {const purple=color('#885cac');g.box(p.x,p.y,p.z,1.6,2.5,1,purple);g.sphere(p.x,p.y+1.9,p.z,.72,c);g.cone(p.x,p.y+2.4,p.z,.65,1.3,purple);g.box(p.x,p.y-1.9,p.z,7,.35,2,purple);for(const s of [-1,1]){g.box(p.x+s*4,p.y-1.5,p.z,1.3,.3,1.4,purple,s*.3);g.limb(add(p,V(s*.7,.8,0)),add(p,V(s*1.5,-.4,-.8)),.28,c);g.limb(add(p,V(s*.45,-1,0)),add(p,V(s*.65,-1.8,0)),.28,c);g.box(p.x+s*.3,p.y+1.9,p.z-.65,.25,.16,.1,color('#ffffae'));}}
 if(b.warning>0){const glow=color('#ff665e');for(let i=0;i<12;i++){const a=i/12*Math.PI*2;g.box(p.x+Math.cos(a)*5,b.base.h+1.02,p.z+Math.sin(a)*5,.7,.1,.7,glow);}}
}
